// autogenerated with generate_bitfont.py at 2023-01-22 00:53:31.774632

// TODO pack into a binary string for performance

const bg_font = E.toString([
0xff, 0x83, 0x83, 0xae, 0x83, 0x83, 0xff, // A
0xff, 0x83, 0x83, 0xab, 0x83, 0x93, 0xff, // B
0xff, 0x83, 0x83, 0xbb, 0xbb, 0xbb, 0xef, // C

]);

const fg_font = E.toString([
0x0, 0x7c, 0x7c, 0x50, 0x7c, 0x7c, 0x0, // A
0x0, 0x7c, 0x7c, 0x54, 0x7c, 0x6c, 0x0, // B
0x0, 0x7c, 0x7c, 0x44, 0x44, 0x44, 0x0, // C

]);

// TODO add justify aka g.setFontAlign
const SCALE = 5;
render = function(text, x, y) {
  text = text.toUpperCase();
  print(`rendering ${text}`);

  for (let i = 0; i < text.length; i++) {
    char = text[i];

  g.setFontCustom(bg_font, 65, "\7\7\7", 8|(SCALE<<8))
    .setColor(0,1,0)
    .drawString(char, x, y)
    .setFontCustom(fg_font, 65, "\7\7\7", 8|(SCALE<<8))
    .setColor(0,0,0)
    .drawString(char, x, y);
    // for a nice 1 pixel border between letters
    x += (g.stringWidth(char) - SCALE);
  }
};

// showtime!
g.clear();
render("CABBA", 20, 20);
