#!/usr/bin/env python
"""
Generate ../bitfont.js from the original font strip, see boxy_bold.py.

The Espruino custom fonts cover ASCII 32..126. The space is an empty
glyph 4 pixels wide, so that with the 1 pixel kerning it advances 3 like
the original. Lowercase letters have no glyphs (zero width), the text is
converted to uppercase like in the original.
"""

from datetime import datetime
from pathlib import Path
from string import Template

from boxy_bold import EMPTY, GLYPHS, HEIGHT, OUTLINE, SPACE, KERNING, \
    load_glyphs

HERE = Path(__file__).resolve().parent
TEMPLATE = HERE / 'bitfont.js.template'
OUTPUT = HERE.parent / 'bitfont.js'

FIRST_CHAR = 32
LAST_CHAR = 126


def column_byte(column, wanted):
    """One byte per column, top pixel in the most significant bit."""
    assert len(column) == HEIGHT == 8
    return int(''.join('1' if pixel == wanted else '0' for pixel in column), 2)


def check_pixel_classes(glyphs):
    """Glyphs may only contain outline, fill and empty pixels."""
    for char, columns in glyphs.items():
        for column in columns:
            assert set(column) <= {EMPTY, OUTLINE, 'o'}, (char, column)


def font_tables():
    glyphs = load_glyphs()
    check_pixel_classes(glyphs)
    glyphs[' '] = [EMPTY * HEIGHT] * (SPACE - KERNING)
    outline, fill, widths = [], [], []
    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        char = chr(code)
        columns = glyphs.get(char, [])
        widths.append(len(columns))
        if columns:
            outline.append(', '.join(hex(column_byte(c, OUTLINE))
                                     for c in columns) + f', // {char}')
            fill.append(', '.join(hex(column_byte(c, 'o'))
                                  for c in columns) + f', // {char}')
    missing = {char for char, _ in GLYPHS} - {chr(c) for c in
                                              range(FIRST_CHAR, LAST_CHAR + 1)}
    assert not missing, missing
    return {
        'outline_block': '\n'.join(outline),
        'fill_block': '\n'.join(fill),
        'widths_block': ','.join(map(str, widths)),
        'first_char': FIRST_CHAR,
        'height': HEIGHT,
    }


def main():
    template = Template(TEMPLATE.read_text())
    header = (f'// autogenerated with scripts/generate_bitfont.py'
              f' at {datetime.now():%Y-%m-%d %H:%M}, do not edit\n\n')
    OUTPUT.write_text(header + template.substitute(font_tables()))
    print(f'wrote {OUTPUT}')


if __name__ == '__main__':
    main()
