#!/usr/bin/env python
"""
Generate image modules from the original Heroine Dusk art.

  python generate_images.py path/to/heroine-dusk/release/images

The original art (CC-BY-SA 3.0, Clint Bellanger) isn't copied here, get
it from https://github.com/clintbellanger/heroine-dusk. Each module in
MODULES is written next to the app's other files, with one function per
image so that it is only decompressed when drawn.
"""

import sys
from datetime import datetime
from pathlib import Path

from PIL import Image

from convert_image import BLUE, to_js

APP_DIR = Path(__file__).resolve().parent.parent


def sheet(path, size, count):
    """Cut a horizontal sprite sheet into count images of size (w, h)."""
    width, height = size
    image = Image.open(path)
    assert image.size == (width * count, height), (path, image.size)
    return [image.crop((i * width, 0, (i + 1) * width, height))
            for i in range(count)]


TREASURE_NAMES = [
    'gold 1', 'gold 2', 'gold 4', 'gold 8', 'gold 16', 'gold 32 (chalice)',
    'gold 64 (bars)', 'gold 128 (chest)', 'gold 256 (crown)',
    'gold 512 (sword)', 'Wood Stick', 'Spellbook', 'Magic Sapphire',
    'Magic Emerald', 'Magic Ruby', 'Magic Diamond',
]

MODULES = {
    'treasure_images.js': {
        'doc': 'Treasure icons, 32x32, see treasure.js',
        'images': lambda root: sheet(root / 'treasure/treasure.png',
                                     (32, 32), 16),
        'names': TREASURE_NAMES,
        # the sapphire's mid blue would turn white and look like the diamond
        'overrides': {(89, 125, 206): BLUE},
    },
}


def write_module(filename, spec, root):
    images = spec['images'](root)
    lines = [
        f'// autogenerated with scripts/generate_images.py'
        f' at {datetime.now():%Y-%m-%d %H:%M}, do not edit',
        f'// {spec["doc"]}',
        '// Art by Clint Bellanger, CC-BY-SA 3.0',
        '',
        'exports.images = [',
    ]
    for index, (image, name) in enumerate(zip(images, spec['names'])):
        lines.append(f'  // {index}: {name}')
        lines.append(f'  function() {{ return '
                     f'{to_js(image, spec.get("overrides"))}; }},')
    lines.append('];')
    (APP_DIR / filename).write_text('\n'.join(lines) + '\n')
    print(f'wrote {filename}: {len(images)} images')


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    root = Path(sys.argv[1])
    for filename, spec in MODULES.items():
        write_module(filename, spec, root)


if __name__ == '__main__':
    main()
