// generated using https://www.espruino.com/Font+Converter
// from https://opengameart.org/content/boxy-bold-truetype-font
Graphics.prototype.setFontBoxyBoldGround = function(scale) {
  // Actual height 16 (15 - 0)
  this.setFontCustom(
    E.toString(require('heatshrink').decompress(atob('ABf/AAnA54BBBIoKBAKM/+AYD+c/AIPAh4BBA4YLLDYYhFAAPM54BNKZfMDoIBE/gBL54BFh//AIYAF4cPAII/H4c/AIJcBAIRJBEYx0BJYf8AIXDAISfGJAIAC+CEBn/PAARGGAAgPDC4ajE/gnCAIXzAIXA+ABBA4YPDCoMP+ABDSY7XDBY4ZFgAhBAIfMAIMMngBBBYhSBOoIBCmYBKCIodE/gnI/kDbIoECJ4fDAISoBAIS1BAAguBUIYADBIK3PQ4b3DC5/PGYKIB54BB4ABCCor+EDYgXDDYg7DAAptDdoQBBb5ZTLI4Y3HcQQbNFYQbSgABD54BDUAgBBKaA3KN7YbP4cPAIIKGagnDn4BBBwsP+E//gBBX4fzn4BBdYYkGb4nMAJgTFIAibBAAQxDHIZBDI4KABAIfDLYK7FAAXM/4BBB4Y3EDYLBIDYYfEVIYBCcKA3CAIb9baJRXQYpQbQdwIBBCYa4CKaA3TRY44BAILHEgBvSBIKLQIYIBFYZ4uDHY4RFgYBFh4BBDgIBFe6ZPHe6Y3HgABDUASiGDYiyDHY4LDLaYjIn4BBD6bmHDafM/4BF4AACAgIBEG6qhDAASbLHY7TP4fPAIPAAIXMEIJDBAIQWGbQjqGL4oLGDIpXJCwyvLcAicEn4BFBYj0DDII3If4YSDAIgLCd56nDD46zKJAJDB+HDCIIZFEIIjEB4YXDMwYADZYfMaIIBEbYZXLZYgACJ6f/MoMPAQX/gYcGE4aXJh/wn4BC/gBC+YBC4fAAIIHDB4YXDDoMD/gBEngBKCIhjCAIQvD/gBCBYZSBXwvMngBB54BG4ABCdwynI+fPAIswh4BBn//AIYhFFYY3HCIodFE4YzHW5IzR4YBCCoq1BEA4vD5n/AIIAECoIXEVgfM54BFJ5SfJ/4BFT5JPJ5hNBF40An4IBBQQoC/gBC5kDAIJHPewoBBmcPAILnGgAbD54BCY6n8AJoTDIQwjQDagBGDZSLI58/AIo3UDY6TbgABBXoQBDDYnDngBF5gBGCopCBHgfzAIRLD+fPAIIPDe4RPI/4BGQ5QzB+ABB4ZRB/gAHBYYTDDIQ3QH6QBEQYfz/gBFR5JDCf4ZIDYwzjPX47PHCosPAYIgG54ACF4wAEH5QAED4YnDAAY1Bf4QBC+YBCNAIBFBYYPHRAkAAB4='))),
    32,
    atob("BggKEg4UEgoKCgwQCgwIDAwMDg4ODg4ODg4ICAwNDBAQDg4ODg4ODg4MDg4OEhAODhAODhAODhIOEA4KDAoQDAoODgwODgwODgoMDgoSDg4ODg4ODA4OEg4ODgoIChII"),
    16+(scale<<8)+(1<<16)
  );
  return this;
};

// edited from the original in https://www.glyphrstudio.com/online/
Graphics.prototype.setFontBoxyBoldFigure = function(scale) {
  // Actual height 12 (11 - 0)
  this.setFontCustom(
    E.toString(require('heatshrink').decompress(atob('ABv84ABJB4gBOAAczAIX/4ABVDYZHLC4/PAIxTMD40/gABBEY8PAIwnD+fAAIJfPCYYfDhgBCEYcMAIRPH+ABCAAZPHAIYADCYYHDCY4fDY5ABCHYYHDXY5TDAIZ3LCY4AEmABBgfwAI3AAIIzLAJYADD4YBHB46/DKYazLc54BDW54TEAIYAC+HAAIPzAIXPAIRLEAIwzH5gBGJ55zDAI4bQIpABBK4YBHT54bPSgoBFKZ7XTN6YbPbYYBHB4gBDB5UMAIU/AIQvDCYYADC4czAKilEAAQpDGIY5DIIYAD+ABH4ABB5gBCR4ibBCYjBPD5ABGcL4XTYI4TLABY3XWYaPTAIY3T5kAAIoYBDQgbM4YBKYb5bDVZ4XDgfAAJL33TggBHDZzvDAIZbbD74bb/kAAJI3cTaTTP+HAAIP8AIQXH54BC4YBCDYbeHG5byKV7ibD/4BDCo4LCV6c/gABFH56fDWbABCL4gTCh4BCA4YPDC4YADYYYBHbYYBHPZ4ADJ6cDAIT/EAASXPhgBCngBCN44HDB4YXDAAglBAKJjKAIYrHmfAAJM/AJSnPDZ4PLmABGC563PDZc8AJTTHF5fMgABBGYgBDmABG+ABJT75PD5/AAJJMEmABBhgBC5/wAJJHXmYBCDYYEBAILHbAKYjbDcDjKG7gnKDZ7mCAJAADnnAAIrbLb44jDb5cwAISjfngBCn4BDCo4LCCYY3bH5Z7DC56PHK4kwAIzjOW44zHa44bDhgBCYY4ADCYbXLB4YXDB44vDf45cBAKo0BGwgAOA='))),
    32,
    atob("BggKEg4UEgoKCgwQCgwIDAwMDg4ODg4ODg4ICAwNDBAQDg4ODg4ODg4MDg4OEhAODhAODhAODhIOEA4KDAoQDAoODgwODgwODgoMDgoSDg4ODg4ODA4OEg4ODgoIChII"),
    16+(scale<<8)+(1<<16)
  );
  return this;
};




// TODO add justify aka g.setFontAlign
exports.render = function(text, x, y) {
  g.setFontBoxyBoldGround(1)
    .setColor(1,1,1)
    .drawString(text.toUpperCase(), x, y)
    .setColor(0,0,0)
    .setFontBoxyBoldFigure(1)
    .drawString(text.toUpperCase(), x, y);
};
