// generated with https://www.espruino.com/Font+Converter
// from https://opengameart.org/content/boxy-bold-font-split
Graphics.prototype.setFontBoxyBold = function(scale) {
  // Actual height 16 (15 - 0)
  this.setFontCustom( E.toString(require('heatshrink').decompress(atob('ABf/AAnA54BDBQoBBAAIFDA5M/+AWB+c/AIPAh4BDBIU8BZU/DYIfBEIZHF5gBEDIIHF5kPKZPM/4BDEIP8//8n4DB+H8AYIdB/gNBAIUMh4mBAIYAD4cPAII9HA4PDn4BBLwIaCEYPPEYp2DIgP8AIQAB4YBCT4hQDKIKGCDgPPAASLFAAILDCIIXDUYQjCEoX8XYQ6B+ABDA4ILBRQYBBEQIBBhiQBBgIBCa4oLFCYIZDAIMA/gBBCQKUBAIMMAAM8AIILCNQQBDmYBMCIYbCAIQlDE4n8gazDAQQKCVQXDAIPwVAKzDUIprDUoanDAIK3HXI4TEZoLPIAAPDDAYxBRQYfBAIgVDVYYzFCoIBFHYwADN4bvEAILhLKZJHFHIxZDDZYrEDaEAAIfPAIqgEKaA3KN7YbP4cPAIYKEagnDn4BCB4kP+ABBn/8nn8CgIGB+YTCdoYkDb4vMAJwTDDYSZBAAQrBF4I6C/47BAgJFDQAIBB4YBBLYK5DAASHCCQQPCGoYbCYJYfDEIizEAILfO//M/g7CYZz9PaJBVOAAroGDZwHBWIIBBCYKxBXARROAII3TRYQBD+HPAITHCgABCOKIHBAISLNIoQABYaSFFHY4RDgYBFh4BDDwIBDGppPIAIT1NDY41FgABFURAbFWgY3Bnk8AYIJDR54jIVYX8n4BBV6LnLS6fM/4BD4AAEAwIBEGqqjDTZw5C/g7CaZwAB4fPAIPAAIYhBAIXPAIQWEHgTgCJAhfGfAxWELAhrKVpriB/nAAIIfBn//AIITBc4IBBBYLyCC4QBBG5D/BAIX/mH8DAQJCdpqVCUoQjCDYIfCWZhKB+HDAIIGCDYQfBAIYLCB4ITBLYRmCEgrJDAIXPAIbbEUIIAIZowACJ6KtBAAX/gYBCAAolDTJIA='))),
    32,
    atob("BggKEg4UEgoKCgwQCgwIDAwMDg4ODg4ODg4ICAwNDBAQDg4ODg4ODg4MDg4OEhAODhAODhAODhIOEA4KDAo="),
    16+(scale<<8)+(1<<16)
  );
  return this;
};

// TODO add justify aka g.setFontAlign
exports.render = function(text, x, y) {
  g.setFontBoxyBold();
  g.setColor(1,1,1);
  g.setBgColor(0,0,0);
  g.drawString(text.toUpperCase(), x, y, true);
};
