// autogenerated with scripts/generate_images.py at 2026-09-29 10:46, do not edit
// Action buttons 16x16 (0-7), the selection frame 20x20 (8) and dialog buttons 16x16 (9-10), see action.js, dialog.js
// Art by Clint Bellanger, CC-BY-SA 3.0

exports.images = [
  // 0: Attack
  function() { return require("heatshrink").decompress(atob("iEQwcBkmSA4MSpMkwP//+AAoN/AoP+hMjAgP8gEBAoXj+EBj4FBj/x4Ef/04/+PAoPxw/8v4FC3/j/4RCm4aBBYWG4YFBkeMnAOBF4JBCAoMkgJHChMkwBcCJoJZEA==")); },
  // 1: Run
  function() { return require("heatshrink").decompress(atob("iEQwcBkmSA4MSpMkwP//+AAoN/AoP+hMjAgIFBgIFCv4FBj4FC//AAoX9Aonv34FEBYf7/4LDAocgv4FBFIIFBGockgJHChMkwBcCJoJZEA=")); },
  // 2: Heal
  function() { return require("heatshrink").decompress(atob("iEQwcCpMkA4MkyVJgHbtuAyVIm///+2iVBAgP//1CoP5k+Sv1Ch/J8mSp/Ih/P/mSoIFBBYQFC/ItBh4FB/8kyF/AoXkwf/5FA//8j4vBAoI1DpETAoOSiRNBKoJNBLIoA==")); },
  // 3: Burn
  function() { return require("heatshrink").decompress(atob("iEQwcCpMkA4MkyVJgHbtuAyVIm///+2iVBAgP//1CAoP8/1+oUP//kz1P5AFBk2SAoX5mmaAoe07YFD23av4XCmwFCoAjByYvBAoI1DpETAoOSiRNBKoJNBLIoA=")); },
  // 4: Unlock
  function() { return require("heatshrink").decompress(atob("iEQwcCpMkA4MkyVJgHbtuAyVIm///+2iVB//4j/+oQFB4/jAoMP/04jl/5AFIgAFDjdsAoY1BBY9ABYV+oVAHQP/F4NIiYFByUSJoJVBJoJZFA==")); },
  // 5: Light
  function() { return require("heatshrink").decompress(atob("iEQwcCpMkA4MkyVJgHbtuAyVIm///+2iVBAgP//1CAoP+AoUP/+//9/5AFB+3b/4FC+/794FB/oFBBYYRFDodAFwPfFIIFCF4VIiYFByUSJoJVBJoJZF")); },
  // 6: Freeze
  function() { return require("heatshrink").decompress(atob("iEQwcCpMkA4MkyVJgHbtuAyVIm///+2iVBAgP//1CAoV/AoMP+4GB3/Ih///d//4FC7/vApIREDolABYIvCAoI1DpETAoOSiRNBKoJNBLIo=")); },
  // 7: Reflect
  function() { return require("heatshrink").decompress(atob("iEQwcF23aA4Nbtu2wHbtuBtu0m///+2luhAgPj/1F0P5k8Yv1Fh/50HLh/IAoOmpNhAoWghEBAoWnhF/ApARBAoOg/82oYvBAoPkz4FB2kTHgOSlpNBpMkJoJZFA")); },
  // 8: selection frame
  function() { return require("heatshrink").decompress(atob("ikUwcBkmSpAIBpIFBpMgtu24ESBAOR2MkyewCgXECIMk8ACBsQaD4GSmIFCC4OBkYgCBAM4iOJBweSuEYAodJk8BBzkCHZsSowODzkJkmMBwVOggLBjYXBncCBYUG7dsRgQIBwEACgQ=")); },
  // 9: Buy
  function() { return require("heatshrink").decompress(atob("iEQwcBkmSA4MSpMkwP//+AAoN/AoP+hMjAgIFBgIFB+3bAoMf/+27d/4Ef/u07dPAqYdB7QdBFIPkyYvDGockgJHChMkwBcCJoJZEA==")); },
  // 10: Exit
  function() { return require("heatshrink").decompress(atob("iEQwcBkmSA4MSpMkwP//+AAoN/AoP+hMjAgIFBgMj+EHgF+gMf+MgyEP4AFBkgFD/0kwALFv4FCC4nwHYIFBkF+gHgh0BkA7DJoMBI4UJE4JcCJoJZEA")); },
];
