// Tile images, split from tileset.js so that each file uploads in one
// piece (see tileset.js)

exports.images = [];

// 9: chest_exterior
exports.images[9] = [

  //chest_exterior 0
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CIyEAggdawEAgAaWDAIABuACBiQdZAAPggQdVAgWT+AdYHAUDDoMcHbgdbWYMcgAdV/4ACaIQd0aIo7dgeADqsfDrkcAgOfDrP8DrgECDsCzXDo8AgjRZAAcCDrESpICBDqY1DgIHBAgOSDqYTFSgMgDqhyEkmQDoOQDqZxBAgNBDoZaBDrNIPYQdZPAIdaaQQdZSwIaTWY8JDq4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4ChA="));
  },

  //chest_exterior 1
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CbpEAgQdaoEAgAdaDgMOAQIABDquQg4bDDrUP8gHCDq04DoPAHbIdCHbOADoMBDrRUBgP/AAQd2aLWBWAI7aDo34DrP8yVInAdcn4dbd7YdXpDMDDq+QdQjRXyMggVJkAdZkgaBA4JAEDqkSPIIKEDqeQDoR8GWadADoWShIKCkDvUkAdckmADrixBDrlJgQdceYKzXAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ARoA="));
  },

  //chest_exterior 2
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CPpEAiQIEwEJDqdAgECBAkAgIdTn/ggAADgfwDqgbEAAYdTyP4A4ufwEADqg5Fj+B4A7bDuf/AAx3VDrmQaJA7xDof4DoazYnHiaLc/DrjvaDpK2SwIdHWYIFBkIdOkEBaJIABgIdNoESoIdIBoNIDpoRCoAyCAAkJDp8ALYkSApEIDpWQGo4AHgUIH4TLIGQYlDBoVICAeCJYgd2gQdbwAdLyAdGwDLDCAcAXoizXgDsKAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ATwA=="));
  },

  //chest_exterior 3
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4COgAIFgEEDqcggEJBAeQgEADqkP4AYBAAUH/kSHagAHDqcAgP8BQsfwQdSgeB/A6FDqw7dDrZ3B/4AGDuQAIgQ7wSoIZDj4dYWYUHjzRbg/+d+KpCDrUyAgKzBDo+ADp8gHgTRIwEBDp4EByAdIxIrBDqGSoA/CAAkJFIMADptBAgcSBQgFDpEALhlBHA4AIgQdKwMEAgWQGoYNDHwYdpyIdcyAdcyTiDDodAEwYdCyAdMdpCzTAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ATQA="));
  },

  //chest_exterior 4
  function() {
    return require("heatshrink").decompress(atob("0F4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4ClyEABAsAgQ7/AVuR/EAAAkfwR3zAAx3z/gHFz53yWfZ38Hff/AAw7/AV2QgAAGgR3/HeUfHe38AgMnjwHBz473/w75A4Y7ykEBHY+AgI7upESoI7HxMggg7toEAgP/AA2AgEAHdoBBoI7HxMkyESHdeRPIYAGhILBgQ7rNYIECwQKEyDBDHdZzHPZQ7nkQECoIHCkB3GpMBHf47/Hf4CdkEJAgIuDkESBoOABYQ7sgAAOHdQC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4Cu"));
  },

  //chest_exterior 5
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CYgAADDrlADrGSoEAAQIdYwEBAgIdZgVBDreSDsCzZDoWAiQdagEEDSzREhIaXaIcCDTACCKzQC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CO"));
  },

  //chest_exterior 6
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CxwEAAAQdYxAdcxMkgEJkgdayUAggdbhJZbDoJZZwIdcyUEDrlIgQdbAQIddyDRZLggdcAX4C/AX4C/AX4C/AX4C/AX4C/AX4CuA=="));
  },

  //chest_exterior 7
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CGpEAiQLHyEADqEH/kABY+P/EEDp2R/EAgEJBY1/4EADp2PCIIAHgf+AYJlIAQt+DhAdCg/gDpsj/xqJz/wk4dP+AdK+Mn/kCDpkf+ANJDqXxDpckDp3/wIdKBYIda/+JDrs/8AdOABeOeYIdawAd/DpYPBABo7czgdTgYdGkgdbxIdQ/IECk8DAockDuoFEDoi5FDpgCGDocJBAYdX8AdDkGADqs/K4kEDq3AgA7CpAdKABeOgCyDoIdWwEAiQTChIdXggTEggGFDqATEhMARRD9FAAzODkwdBgIdIWBACHmmShAkDDq2kyUABhIdPpoCBDrOTtIFBeYYdOmwFF7YFByDzDDpcm7dtNwIFD23aHYOQJZRZPAQOEDqNNHYQIC23TDqjICMQgdCJZYdNkgdBkIdchIdbpClMDttCDqgCG6USDreQB5wC/AX4C/AX4C/AUwA="));
  },

  //chest_exterior 8
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CTgECBZEAggdPpEf+ALHwE/8ESDp1Agf+hILGgEAj+CDpwSBv/AAYIAGgZHIAQ0H8AdKgF+I44dH+EP/gNIwF/4IdMyE/+QdLh4dbyEP/AdOyQdKBYIdQgIdKgP/Dp9B/4dZg/+DrbjBuP/ABYdPF4Id/Dq4ANDps8Hbk8yAdG4AdUyTvBDroKDp/A+QFDDs1AUYgdI/4dOAggdHAQodJokSDocHDq+ALQn+Dq58EgfBDquChIHCHgNxdAoAGDpNBA4UggEBDqlIwQHEwAdVpMCHYckyAdWkQdB6SYEABYdIkgdBzStIAQ4JJwMkyYdcyVpDrORAgNN0gdYyQEC23aBQgFFDptkHYM27dt2y5CyYFEDptMAgJZaDoWm7YKEyaeHFRYdCKAraIDpcyDoIKFDqkmDrkk5Id6zIdcycmd7ICCsgdcAX4C/AX4C/AX4CZA="));
  },

  //chest_exterior 9
  function() {
    return require("heatshrink").decompress(atob("0F4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CkgESBZEAHd1I/+CBY+R/8EHdtHHZfgHd+AgAAGgI7w/g6HAAM/Hd/+BpI7/Hf47o+QNJk47/AVU/HZf8iQ7/HdP/ABQ7/Hf47/AUUAABh3/Hd/4j47/HeHyA4c4jwFDk47/HdMAHYs//w7FgEJHdMipA7FAQo7BpMBHdMSHZ8gHdFIgCzGHY4PBgg7nog9BO50kwA7nPIU//4AKHYWQiQ7lyI7SyVCHcvJHadIHckmFIY7QpMJHccyHYcAABgWDkI7jA480DJw7ipg7R6QFEwg7hsgHGpu0GQMmBYkmzQREyA7gyYKHpukHYM0zVNBYU2yYRFiQ7fzIEBtu27YCD0wCB0nbpu2IIM26YOCtIXBoQ7f5MmHAg7FBYNJBYY7DAQOSpA7ekwcbhI7dmSkBOgdpPQu0QYvaRI2hHbwHFboQID2naBxkhHcgCGmnSBxg7tDho7sARw7/Hf47/Hf4C/AX4C/AX4C/AX4C/AX4C/AX4C/AR4A=="));
  },

  //chest_exterior 10
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/pMADrn8gQdb//wDrn+hIdb//BDrn4Drn/ggd3gF///gDrUPDreAgP//kSDrMAn4dayAdcyf/44dayV/4//wQd4/Adbp4d5WYIdb/4ACDv4dY8ECDrXAj47awE/LLUAv6z/Dv4dU5/4DrXyp4dbyQd/DrmJCBOQDrnQDrcmHbm0Drdt0gdX7dt2wCBDqeNC4QCFWbgdbk2StIdPyf/AAIdH6QdQz4dJmw7RDgXgdg4FCwgdQiSSGDoYaLDonABQuTdgIFBkIdP/wKGDoIFCDqGBBQ2bSQIFBhIdO/gKH7YFCpAaMAQXiA40m7QFCoQdPWA1J23SAoQMHARAHGpodctumAoWQDRodIZwMmAoWEDqAA="));
  },

  //chest_exterior 11
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ATtADreQn4dbx//Drd/Drcj/4dbj4dbpAcBDvFH//+gAdb+Adan//wEEDrX8gAddkgda8f/8gdYyP/DoI7ZDr8fDrv5DvSzcAAQd/ASmQg47c/EDLLn8gJ3c/0AWf4d/DqUf/Iddk4dckgd/ARNkBRNBDqNmDrlk6QdczYdcydtDru27YCBDq+SDogCDsIdULLeSpskWwwdVkwdIAAPkHaPaDpP8DptMAgTyGpEHDwQdNpIdDTA0gDqMyAgLyB0gNFgYdTagIdGyF/Dp8mAgVN2gNGgIdPknJAgW2Bo1In4dPzIECmzyGpMHDp+TLwfbBo0gDqtpBowdPyVkAgXTeQwdRpgEC6TUH"));
  },

  //chest_exterior 12
  function() {
    return require("heatshrink").decompress(atob("0F4wZC/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4AHgVJkmSATA7eiQ7bkA7dFhs0Hxw6cgg7O6Q7NwA7bUhtNmnaHZuQHTUBkmbtu27YCBGoIFC2mTAQILCAQY4CBAe0yQ7ahM2FgwCG0hKFAQXaAotAHbKhNASVIHTECHcFJHbESExWTGRkm6QIGkA7XMRY7B0gOLHY8kHS0EFhebVpvaBA+AHaosMzdNBxmaBA+QHSkBFho7MkyGJHakJUhp3NydpBY9AHabgOHZvSHZFIHSUCHZkmFhI7Ftu2BY47SiQ7OQxuSpu27Y+BAQOkydJkA7RFJg7YAQW0HSEEHbwCKwA7PEB02HbWQHR0BHZ44XAQY0HA"));
  },
];

// 10: medieval_house
exports.images[10] = [

//medieval_house 0
function() { return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CmggdcgECDrgAHIigdlggdckmADuOADgsBkmQiQdSyAdFhIdVyQdGkAdVoAdEpMgiUCDqdIDgYZBDqy1EKoUCoAdUkAdckgdCAoWCDqzyBggFDpDVBDqbyBDrbyBBQeQhMBDqtBDsOSDrtBkAdbfAIdSJ4Q1BiQNEXQYdOoAdDyVIDIYdSC4RZEwAdUpMAaI0IggdTOgLvGDqkkgSzFgIdVaIwddAoIdbbQIdbpAddO7gd/DulIgAACDqIVDAA4d/Dv4d/Dv4d/Ds0BDRwdMiQaPDpYaRDpQaSDpIaTDo6PSAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CbA="));},

//medieval_house 1
function() { return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AQdIDreQgAyUgAAHDuWADrdEOAId4AIIcGggdVoA6GDqkSDosBDqeRkESaYsJDq1JDogKBDqWJgAEBkAcCgQdcIIIdUggECDoQFCDqVIDoeAdgIdcBQYdRkVAA4eQdgIdayTsBDqtBDrcSC4gdYA4odVpAHEkBBDTAIdUwACBDoWQAQIdSd4hZCEYQdRwDRHgQdTwQdGPQIdURgIdEgCzUDo7RWC4gdXZAQdbA4odWcwQd/Dv4dSgAACDroAHDv4d/Dv4d/Dv4dapMgDrgCBDrtJDrskwAdcyVADribGDq4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C9"));},

//medieval_house 2
function() { return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C7wQdcoAdbkVIhIdaiVJgIdZpAEBkAdZogECgg4WgEAA4eAAwIAEQBwdBOYmQDqtACAWQCYQdVCAJWCoIlDAAcBXh0AgQEBgVIP4gdRN4LsBkACBWQRYFDpqrBC4TvCAQQdTGoNIdYY+BkgdSdgVAA4eCeQodNkANCd4ryFpIdMdgwKCeQtAkAdMKAQKFeQodMpDsDBQzyEDplAdggNFeQcCDprsEUAwCCDprpDARcChAdKyAaMeoYdLyIdQLJYdRTYJsJDqUkDpbhBPgIDBAAcJBYeCAoIdLdgWABotBDQNIDqUCBooaByAdChAdOkAgCBogWBDQIdQgANHkGSoBcDDplIBpILBd4TRNF4LOLDp8BDpOQDoUIDpmQYQINIyQLBDpzsGeRAdNdgzyHDpzsHDv4d/gEADpOQBgIAQDv4d/Dv4d/Dv4AJDQwdVgIdchIdcDQ4dUgQdciQdcDRAC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ASgA=="));},

//medieval_house 3
function() { return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C+yAdcxEJDrdJgIdakVJkAdaiQEBggdYpAECwAXRgAAFG4eQAwodSBogdXV4VAAQQIBVRwdFdYUIG4NIBAKcCDqJ0CpI3CDqBNCAAMCBQOCd4IZBkAJDDqAxCAQQZCIoYdQA4Mgd4YCCDqTHCd4ibBeQKfCDpSnCdgVIBojXCbYYdJiEIdglBBojyEDp5MCJ4tIeQYdPdgYNFeQaBDDpEJdgoNFeQgdNdgoQFeQYdLoINLAQeAFRAdDM5YCDyA/CLJIdPyQdJpCPBDrYEBDrh3ByDxByVAAYIADOgILCDpw+ChINFI4UgDpeQDoVIGQIQGboQdQoMkTYIQFkDrBDppWByBWBCgIQGDIIdMwDvBEAIRBCA+ADqDULI4QdMO4IEBdhUBDqCVBDpNADqDsFCAwOBDprsHeQ4dbWZod/DrEAgIdcACId/Dv4d/Dv4d1pIddkAdckgddwAdcyAdcyQddoAdcAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CN"));},

//medieval_house 4
function() { return require("heatshrink").decompress(atob("0F4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C5pEEHfNEwA75kmQiQ73yIEBgQ73xIEBoA1xyEAAAYKCpAIEPtg7EGIg72iVJkACCHeoHBgmCBQI70gjsBA4IKBwA7vGAYHBoICBhKCFHd0BHAY+DHeRxCBQS2ByVAHeIEBwQKDeoQ7uFoMCAgMSBQcgAQI7CXoQ7qHAI1CBQYICHd6tDBQi5CHdzmCBQ2QfoY7qUoIEBoINHG4OQgEBHdQrCNRBECHdijOoA7rCB1IHdUiCB47/Hf47jpEAgD0BAYIADiQLDHdgECggNFwQCByA7vHwYCDHAI7xoINHhI7xGQINGIgI7vVQQNGBYY7rAgOCBpMEAQI7tiQNJkA7uF4QQJI4I7sU4QQJX4I7rpAQMyA7/Hf47/Hf47/AS8ggAAOHf47/Hf47/Hf47/Hf47/Hf47/Hf47/Hf47/Hf47/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AXoA=="));},

//medieval_house 5
function() { return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4CQggd6wAd6yESDvOSgQd6oAd5iVIhIdbpMBDrSUBDrsgDrUADrmASgMEDrOQDrqUBwAdZyQddgEkyDzBDrFIDrgECeYIdboAd6pDzBDumAAgMCDrQZBDrWQgIdbyQddgEkwQdaoAdcpEEd7dIgAdbpIddkESDrjRbAgId/Dv4d0gAdYgAADDv4d/Dv4d/Dv4d/Dv4d/DrUSDSodFDS4dDgQaYAQUEDTIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AQQ"));},

//medieval_house 6
function() { return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4CtpAd6ogd6kgd5yId6xId6pMgDrUiDr0ADrUSDrtIDrVIyVAggdcaLVEyRYBDrcBDrUkyAddAgIdYyIEDDrGJDvQEEDu8AyVIggdboAdcgBZcgIdagmQDrsJaLeAd7kADrkCDrcgiQdbgAddAgQd/Dv4dugIdcgAADDv4d/Dv4d/Dv4d/Dv4d/Dq2SDrtJDrskyAdcyVIDrgC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CiA=="));},

//medieval_house 7
function() { return require("heatshrink").decompress(atob("qF4wcByVJgMkAYICXAIMgDrkkggdcwAdcyECDreSgAdcoEJDrdIajAEEgAdckDUXA4sADq9BA4eAaizOBA4eQaiwXBA4kAaiuAZotAgAAJMpQ0GpAdWA44AJoAdJFAO26TyEDqkStu27TyFLBAdK7YdB7dpeQgdIpC/JDodteQoAGiQdP2jyEDq+2eRYdRWwbyHBAIdPWwgdHhMBDp3beRMEDqTUEDrDUEeQjaBgIdR0jyHDqjyIDqjyHDIUBkAdReQwdWeQ0JknSgAdSeQwdB7QdKA44CGgACBDrWApMm7VAkkEDq2QDrxZBoEEDrT1BDvVIDpL/BAAcCC4QGCgIdEpMEwA7Ipu27dt0gKDhu0HYdBa4gdHDQIdC23SBQVBBAIdCOgIdRC4RuBm3btIdDMoQdPLgcGDosAhIdROgUgAoIdCTwQCBiQdO2wNCjYdE7VAkAdRTAWDDonbDoMQDqHaWAQdCoMmDoMEDqK2DhodZWALyBDolIDqZWBCAWQpIdXeQQdCmwdWeQQdFgDRReQodaeQQdBXgQdVeQYdZeQQdFSqbyDyFNDrLyBDoRfBkA7aDv4dyaIQdZ6QdE6UAAAIdRKwIQCDoOwDgQdRKAIdEoAcDDpAMEAA8BDofgDq4AIDp0B/EAv///+B//guBZUnAGFDv4d/DqkHdgbvbEwgdYHaF+CIkOgH/AAWADqAXBAAcB4AECj4dRAAodEgYdjDQgdUagUEDrIACDQodRBIodSh4dIhIdSAAtwAYQaGDqsCDqBWBgf/AAfgDoTsHDpMB/AGEg4dDDQ5ZKnAGFDoTsIDqgaIDqbsJDqbsJDqTsKd6TsKDqTsKAX4C/AX4C/AX4C/AX4C/AX4C4A="));},

//medieval_house 8
function() { return require("heatshrink").decompress(atob("qF4wcBkmSpICXkQEBDrUSDrdIAgQdZogdbyAEDDrGBDrkJDrcgA4gdXgQdbpDsCDrNAA4rOWggHDTAIdVwAiEgIdWC4IdDgAdKBgIAJdgmSgEEDqqaGHgIdIxAcJdgrWBDqrsEk3bpIdKxIdJCAk27dtkAdJFIIAHdglN2wdB2wdKkAdHCAgaBDqrsEzYdXdggaCDpskdhSwBDpsioIdGdgiwCDp+AdhIaDDqjOIDpjIByDsIDQgdTBoeTDq7sKDpcSC4TsNDqTsKDpcQgMmyVAdhgdNmwdCdhYdPpDsEARQJHpGQhM26VIdggdYDRgdLwAdBAgIdaAgQd3AgYdXomCDosAAAQQCAwYJFDooEDhAKDzdhAoeTtu27dpHZIECwAdDCgKACpMm7YdCAQIdKgAdDpu27AQDDQYdMoAdG4RWFDpkkyCCByAdCCIMSPQQdQiEJmwdE2ANCDQodKkAdB2wdEwiSIDpeADoPSDoVsBoU2DrDsDDQwdMCgIdDdgS2BDqtIBQgaHDp3aDojsIaJcADo7sIDqgaIDpcCVQQdDdhIdTdhKVLDo4aJDp9odhgdLiRTCDoQaKDqQ7dDv4dZaKsAgEBkwdEAoIdUAAMbDoZcMDpcAhANFMQIdSg4dDEogAIHZgAQDpkOg//wP///+gEfwAdVCgscHawd/DuryB8AdZChDvVDrsB/4ACgFwBYl+DqP4AgUDwALEEYgdN4AdJLJlADrlIZwQdZpI7cpMgCI4dUkgdI+AdTGQUOC5IdPyAdceQUOg//AAfALhAdKeQIdB8AUEj6YHDpTyBDoIUFjhZSeQIdckAdckgddwAdceQTvYeQgdbAX4C/AX4C/AX4C/AX4C/AX4CnA="));},

//medieval_house 9
function() { return require("heatshrink").decompress(atob("0F4wcBkmSpICZomADrYCdkmQiQ73yIEBgQ73xIEBoA73AgVIhI71kQEDgI71iQEDkA70pAHFgg7zogHFwA7zA42QXQgCtyIKHgQ7xxIECkBzDoA7xAgcAOYdIhI7vkQ1DgmABQcBHFWQgAACVogKBOYcgB4b1mwArDBQZwB7RzEB4cAHcopDgh/DhO27Z6BJg71lFIYyEpo7BeQLEHHcjeDVQkCto7BtK8EHYYSEHcZkDkEbHYVtkESCYVAHc5kDA4g4BHYW0gQLCpDGHHcQvEgw7E23AJ447mU4k2HYvYX4g7lT4YHDgI4DAQboECgUEHcglDyENHY9gCweAHclATouAHAoCCthKERow7fUgkDHZFtwAWDHcgjBhIHCkEbHZOwiSOFAwY7fA4cAHA4CDgQRCpA7kFIkEHZfAJog7hyAiEoEmHZfYYohUEHbwHDgM2HZfbgIZDHcOAghADhI4KAQVgDIkAHcAEEpo7NthQEHcCeEASsAewYCbD7VAHb4capA7/Hf47/Hf47RgAACAoOQAwYAFGoQGDHccSpMm7QFBwdt23bAQekCYMEAQM27dJkA7kpu26QFBjY7GBYQ1BJoIIBHckTF4IHBkA4FAQiJCkgFB0A7l2gHBgw7K2mCCgObHcqtBcYNIcAI7J23YCgOTtuwHcoHBoI4JAQY0CHcsTtIHBho7NsIRBpo7lAQOQHBYCCtgZCHckSAQODHZ1twgZBmA7meQI7OOgNJkA7jEwQ4NAQZQCHcsGHaPCHc1Imw7R7A7moI4PAQY3CHccNHadhHcmQHCICCtg7kwY7UtuEHccTHaugHf47/Hf47XiQ7V2A76O/Y76tMgHclJHaXSpI7mA4J0PDIQ7kgAAWHcI5XAAY7fv//AAfwg4GE/ED/wxBCIP8gPHBof+Hb9wMAcf+E/NAk4jgGEjkP//gO8YsEgfwnA7MhyzlEotwHf47IgA77AAw7tHRg7mACo7/ATd////+E//gnBgf/4AJB/EfAYMACIQAB8AFC/x3iuE/MgcBHYOAAwU/gYFCBYPgvyzlHY59CHYwAB8FwHc04HYvgAwcHHeYvCHf8AHdsAHaYEDHcYAMHfYAKHf4Cbv//AAfwn4GE4EfAwn8h4FEHcFwcAcD+E4cAcB/Ef+BvDjkOWddwnAFDHYMcBog7zgE4Hf472GoI7yAA477IJY71AA47fAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CbA"));},

//medieval_house 10
function() { return require("heatshrink").decompress(atob("qF4wcB7dt2wCEgECpMkgmSAYICNDssggAdb0AdCwAdQzYdcyYdG2gdUyQdG20AhMkyESDqFJDrs2DovADqskDrq2F7EBBoMCDqSYFDrFNDri2FgAIBoAdUkwdcWwgdZyYdCsAdYWwdggmSpDzBDqiYCDrc27dsDrS2BDrckzdsgAFBgIdXWwOADrWSpodcpIdCkAdZkESDqeABo4dU4BtJDqLpBgDpBCA4JJDo027bpBKYIdX23btuwgAdXpodC2x6IaoQdMDQIdCPRAdVtuAPQodOyYdG0h6FDp2bDo22yB6EyC9IAQgaFAQXSgAddTAYdYoAddgGSoIdY7dIDoIgBDrYCBDrFogESDrVpDrltDoNJDrUggQdb0Adc2EApMgDrO2DvkJkgda4Ad67EBDvUADrfaO7naLLnaoId57Yd/Dv7R/Dt3SCAIdaCAWADRQdNkkAAAQdXDYcH8BZVwAcDh/4gAdT7A4E8fwAgIdRtgbDgFwnEDDqYbEgH/LYIdSsAbEv0//gEBgZ8CDpobEg44Bn/gDq6qCgE/A4QdU/5uCgE4DowaKDocP/5cEDo47Nj/+WQodG/gdZPoYdOOgYdHvwFBDrJZBDrf8AoQdVOggdRYoQAFgP4DqMcDg8D+PADrX8gIdCAAIaKDpZZBDog7WDovgDqcDXIQdDg47UAoYdDSqkH8AdFAQQdRgP/O41+Sp8fwAYCn4dXOgcB/C1F8AdSOgIdGIINwDqAaCdIgFDDoMEDRQdDJoQdFh4dDDRaVGDoomCuEBDpzpGAAImDuEJDpxxGWAQJDDRgdKg4IDgQdXZwIACZxodGdgoACDRodOdhwdIWAM4AoQaODpCwBDoTsPDo6wCDoTsPWY/4DogaPDo0OAYQdBdiAdGuCzEdiAdFWAIdEDSAdFWAIADdiIdEWAQADDSIdDWAa3DDqqwDAATsSDoawDAAQaSAQQA=="));},

//medieval_house 11
function() { return require("heatshrink").decompress(atob("qF4wcBkmSpICNpAEBgECtu27YCEDuFIgESDrFEDoUTDsm0DqmbDo2kDqABBoEAKwoCBkgdbBoIdTgwdF7QdcBoQdPyIEBgE2WAodcBoYdYtIdTxMkyEBWAwda6QdcBoodShodC0gdVAIOADoYNGDqoNHDqR0B7QdcWAodRkQEBgFt2gQIDqMDWA4dVtIQJDp0SDoQQKDqEgEAQdaBQ1IghZUBQ0AgwdQpAKIwEBeoYdWkD1B23aDq9IgEbDoPbDp9EOhHbDoT4BDqh0CDodtDqkggYaDDqx0ByYdG0gdNOgskDQgCC2gdRyEBkwdH2wdRSQIdchIdZhMkgAdZDQICBpIaGDqQEBDrkggFNDrcCDrMCDoQaHDqcAiQdciYdZiVIgEbDrgaIDt+SoAddgwd5gE2DvGQHbtBDrkBDrkJDvYaJDv4d/aP4dkpMmDrNEAgQdZoEAAAOSDrEH8AeCgIdXgEf+AeCgEDDq0Ah/HHwcAXIwdQ4EchweDgAdWO4P/DwkADqUBDoMAn/8vweEhodUg/8HwJ9EgAdTgH8AQK8FDptADoscAYUPPoY7UDoYAB/4+BDps/DpcAv/4HZxxCDrUcZYgdGh4dQLJYdRgB6BDrZ6GDq8fwAdHgIdSgePPQYAEnAdNoASCgeAPQYdTCQYdBPBAdOg4dcgHgDosPPQodPSoY7DnAdUDQQdEg5ECSqV+O43/IIgdX/gDCgP4DqC2DAAUfwB6DDp8OGogdDPQYdNpAdCLIoFCEAIdOpIdD+AdGQYQdOkAdBCgQdGSp4CBDoQUBDoz1BDp4UEDo5ZPkmQCgatCDqrUCAALUCDq1ADooAFDqDyBDrbyBAAMcWwgdUkAdCWwgdUkgdDWwYdVVoIdCj6zVeQYdCgFwDqzyBWYcODq9ADoa2EDqbyDAAK2DDqbyDAAS2CDqjyCAAS2CDqjyCAAa2BDqrsEWwQ="));},

//medieval_house 12
function() { return require("heatshrink").decompress(atob("0F4wZC/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4AgA"));},
];

