// Tile images, split from tileset.js so that each file uploads in one
// piece (see tileset.js)

exports.images = [];

// 12: tree_evergreen
exports.images[12] = [

  //tree_evergreen 0
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AXeADrcggEAggdcHbodcgIdaHQIABDrsSDv4d2SrsCDrcIDrlASvYABDrkBDrkJDrjv5Drx37d7kBkAdbHbodfhMAHbgdeeSwdjhAdbgVILLyVYgMgHoSzciTRdd/Y7cSrlIWboACDrkEDrhZdHbckHbkEgJZcDrsJDrQaUDo0CDSoCDKawdkpAd6hA75kDTBDvEioMgBAhfVkUAgEgAQIADgQdSDAkQDrcEDrhZeDrGAK4OQDrI9CgUIDojRTAgdIDYUBd6gBBgh8EDSRZFHYcSDqqSCDoQaUaI8JDq4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CLoAXUA="));
  },

  //tree_evergreen 1
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4CVgAdboEAgEJDrg7dDrkCDrEgiA6BgEBDrAcCAALOYDvRZdkgcDSrEAwESO7kCWf4dVpEBDrkJLPKV8DrlADvRZdSvYdcyAcFDqwcGDqsgDvRZdkmADrizdyQYBgg/DDqh2HDucgKwjv/O97sGAwYdZiBZWgEILLkJO8KzXoAdcd7wdeyEIkAdaAQIddAQNIgESDS4dhyAd6iA75oGSgAd1hICBomCoAaTyEAAAkEAQIdaAAYd/DuckwCYBdKgcDoMAgQKBd6kgDoQKEDqhUCHAWCDq+SHYZZXAQQdCTAQdXDYTRVAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AQlABZAA="));
  },

  //tree_evergreen 2
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4CJgAdboEAgEJDrg7dDrkCDrEgiA6BgEBDrAcCAALOYDvRZdkgcDSrEAwAeDgh3bwAddWbcESq9IaIoABDrkCO7QABiQdcSrMBkDvXO4wdWoB3cDo7vzWY4dVHbodcyAcHiUBDqQcHAAIdSkAdJeSQddLJQdTwAaHIoQdRWY8JAYTvSDQbzCpICBggdQOxbRRDpZZRd9SVRDhSVYggdTdg4YBBIsBDqoAGhJZNDpxZWHagdMgVIHZ2SoDtLD4LvbDqWADpUSDqGQhEgWCgCHDosEDSYCEVgJTRDtEQDv4dYyAdboGSdiwdLeSuQgmCoEAAAoaPwATCGgIdWkATEgEIAIQdRGY4ABhAnFKx4AGpI7QDZIAHDpOZHQkBOgKVCP4VBkAOBBgIdKHoQNGhIFEgAGFDpC4GBAx8BDpPJAgNIBQlIDo2QgQdTawIdSLIVAR4gABiQdFAwodHyDKJEwQEBdhQC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CdpA="));
  },

  //tree_evergreen 3
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4CHwAdbkEAgEEDrg7dDrkBDrGQhA6BAAIdYDgcAiTOXDvWQiAdbyUCoCVawAcDgECO7gddWeocEAAQdcgJZbgEJDq7SESrEIaLRYFDq0gSox3VDo7v0aIwdWgGQDrg7apAcHhMADqQcHAAQdROYzyWDrpZLDqVADrizFiAFEd6QUBgQ/BiQcDgQdQwAWDLo0SDqoAHd6RaCd7UBHbTvLSqwdWdgqzHAAQdTABEELJodOLKESHbIdCgR0JHZ9JkARBhIDCAA0Bd7YdSLBcJDqFIgkQOioCGyAbEgQaTAQpTSDtFIDvUIHfMgpDsWAQdIDq8AAAkCoADCDrIHGDqsSgEEA4kBDqcChAkFAAQdTOwQAHLKQALdJhxBiRXBiQKBwBVCDgcEyVCHxSIFoINGawYdLwIHGHwQTGDpeQA40QBooFCpAdSgEJDqeSTo4ABTYYjCLJeSoCJCWATQJDpgC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AXcEDrg"));
  },

  //tree_evergreen 4
  function() {
    return require("heatshrink").decompress(atob("0F4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CVoA75yEAgECHfUSHf472d+1Igg6BAAI72HQcAhI70oA7/Heyz7pI7EHGazCkA7DgLv6HfMId+x3FHeo6EAAUSHfSz5gEEHe0CHYTv0HYS3CgI70OYWQHew3Cd/A7HWe4AEiQ7yoA76O/Y76HQ8EwA7wHQ4ACHd9IHZR6BHf6z1HeEgHA9AHeMkGQMBOQg7CHFoCCwA5CHAZDCHdw0EAA0JHfSzvpA7LegI75O91JGgkQAokBd+arBPwg7uc40CWo47xABECHdeAHZsSO/472O9mQGAWSHZI4pAQioCGYVAO+QCBkCyKgh3ukkChDszAQ1IHIkBHGICFVuI7/AQskHf4C2gh3/AWuQkmAiQ71hA74gAACgMgyAGDgA7upA7EPIIFCggBBHdtAHYcJgECIAUEiEAHdqrEAAr0BgD1sc4oAIgQ7rNQIANHdUmpMgdgK4Cgh/BAoNBWQQMCHc8yA4tIOAsEAQI7xARI7/HdcgcwI74gECAoOQoDyFHdUgAgVIGoIAFgILCHdQC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CuA=="));
  },

  //tree_evergreen 5
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4COggd6ATsAgEBDrkJDrhZdHbodbpB37gQdcDTIdhd/5Z3iQd/DrECaLoABEDIdDLjIbBwEALLUED4IdZgMkLLcBkB3dLYLRcd7od6WoIdbDTAC/AX4C/AX4CRwVJkAdZgAADDvUIDu8BDrlADoNADrESoEgSrWQgEkgESDrQABDSwCCwCWBDS6VDgQaYAQUEDTIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4COA"));
  },

  //tree_evergreen 6
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ARNIDreQgAd/AS+ADvRZdyVAf1YC/Ss0ggCzcgGQDrg7cwAd6yQd5kECDrOQhLvbSQIACDvEIDrSwBEISVZgEJggdZOwaV3yVIDrhcDDraYBDreSoAdcpAd6AX4C/AX4CrwEAAAQd24Ad8gQdaxAbBhCVbiEJkDUZgGQHQIdZoB2CDrNJkEAggdakhaCDrWSpAdcAX4C/AX4C/AX4C/AX4C/AX4C/AX4Cu"));
  },

  //tree_evergreen 7
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpICEoEEBAwCTFgcJDrg7ZwAcBgRZcDrsSDq9IYQiVWwEIDojdISSAABEITyVDohdCDqocDgVAAYKwYDoIDCHbIADO7QdYyAdGO6odGd6sgV4YAEiQdTDAcQDrgYBAwTvZpLv0Dg53VDpLyTDhTySDpUJaKwACyVAgCzZBINAawIdSyByEkAGBDqZZEDALRgySVRWRWADqKpBABJZRDpSVSpAdKgEESrQABDqLREHIZjCDrRFCd7KBDDrIADDrkBDp+AgB3HAAUJeRxWLTQodbiQdcXYYdbggdcLLMCHZ0kWJwdOyByNDqxFChJIEO5YCBKY8kdQMgBAUBd7g4LDt7vaXAwd4LJbEDABUBkD0BDqcJkGAAogdOhJOHDodABwKzRDQVIkhbGDqIwBPhgdPThhcJaKJnDDrECDrkSLLmSDrSuByBbBLK8SCQIEEd6MEwAJDDqZQBOIpAHDo4WDS54dKJ4gAJBwIaJDocJCIQAIDRg+ODSICDpEAcoIaWAQodewAdbPgId/DrOCWDMAehL4PB4YdWyFIBoUIDrANDgMBA4odPkAOFDqwOGDoKaDAAwxBDp0JkGSoAdaCAIdGgQSBkkEDpy4CXYZyDpQdBdhAwGKpASBqVAQgQ7NAA8JCQOKoAECDqgSDHYIaGDp4SD0ieBDpIeBgSsGCQ2UyS1BDpIJIAQw7BiQdZAYOQBpWSogvEAoNKAwIPCBgMEwgdLpADBkoHBosiqQNBxJ0CQ4MEDpZaPTo4dUpEBDvUJDrcAB5gdPgQdNpEAgBMKyESYBoAKCAWAcKAC/AX4C/AX4C/AUgA=="));
  },

  //tree_evergreen 8
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpICQoEECiQCHHAcJDrg7ZwAcBgRZcDrsSDq9IZwiVWwEIDojpUSQgAEeSoddDg0AWDA7iO+eQZgJ3aDoUgd7EggVAGwI8EiQdTOQZ7EDq4AFd/4CPLBB3UgB4JeSSwGAAbySCgOQDo8JaLcAWa8SoAECgQdTLAIDBiUJDqxZChLqBHYbRUAAS2FySVRSZMAwAdRKQazZDpSVSpAdKP4KVUAA4dRkDSCDrQSBDpDvSdgodXABQdcgIdPKoKUKhLyOKxbyEDp2QDpkSDp0SHpwdKpANBAYYdZAB6VbeRwddWRJIGDqDkCwQJCQgodMyQdDhKfJgKVRgMgepA4OABwdLoBmCWbIdBgi0JDqCLHDudJkAcPbgQdmgAdBhLvDkmADqMAZo4MBXJAoBSR8CE4KVRDobwBWa4dCyAdZWAUSeCKVJR4QdYKoaiCLhyzNZZBZPkmAK6AdLKp4dOSiIdMkgddPRwOBDpsJCIQ4VHxwaRfAr0CDSoCFDr2ADrZ8BDv4CNyCwDDq1Ac44ACegkSDrkAhIdbggBBwQdTgKCBAgUEEQMCDrBABBIgdHiAdKyRjIDpcgCQkJkBJIDo9IJoYAFhMAJJC2IyEBiVICQoGCpAdPkEJkVJCIkCbZbyIhMUAYLoDABYdJxI7BbBgdOkmRMAYdWDYIfBAwRcKBwIdJyY7EAQcSoEECowdJyVkegIMJDqFMwQEBAwQKBiVJlJHEAoIdKpECTQeUBQMiqQXBGwYOBJJYdCLRwMLkAd6SYYdawIdcYwYdZfpdAgEADp9EAgQVBABJLPAX4C/AX4C/AX4CXA"));
  },

  //tree_evergreen 9
  function() {
    return require("heatshrink").decompress(atob("0F4wcBkmSpICZpEADrYCcwBfCLjo7dhI72yA7CWfY76gQ72OoQABgLs0gI7EgA70HQoABHew/EHeWAGwUSAYUEHecCoA7EO+tIgECd/QAEHeWSHQzvzHYUkHYY4xAQLuCHYj0BHeSuCHfUAyA+BAQMSHeOAHYUQgJCCd+Q7DgEJAYQ7xkDrEd+o7JAAMEHfR36gI7vkg7JhI7wwA1CyA7EHFwCDc4pCCHeJwCkGQhMEPQMCHeEgdxESoI7uoA6IgEQgI7upA7JgEJHfTvwHZS/BHd0gHhQ7vkg78ySrBAAUCXoUEWeESW4gMCwA7xABI77dluQNYI6JgJHBOmwAEHdmSHRkCHdcEyVIPJ0SHc5pCoA7OO9A3OI4SIBd9LtMoJ3rkmAGwz1EgSHDHdOSOIwJBgEJkCHEHdsSpLkHPoTvpAQNAOgmQIImQBgQ4oUYY7CoL2IXAJ0rABw7pb4QAPd9A7SgDvoHf6z2AQI6PgI4nHZcEHd9AGIMBkCoGyA7skESoBsHwQMBHYsAHcyvIpKwGAAw7sABq2kHa0JW0g7npA7RkAnBpCz2G4cJkGAd/IGBoA4MyACBdkQCCFAUEO5T/CBwUCHcq2EAA4zCHwg7npMgHZMSXgw7okiyKIY47oeQQALiDxBHEw7DgMgF4IAIHFR6OVtICKGoI42AQlAHfcQHfNEyA7/Hf4CtGoY7EwQ4ugAAFgmQBA0JHdMgFoMBHZkBHdItDgg7LgA7opA7DPYQxCHY8EHc9ANpIJHgA7nGBBGKiQ7lchEBkkSXwYAEgQ7l0g7IkA7JgA7kkp4IhICEXw2JHccpcpDsIXweRHcYDDGhLtJHcVKAwg6NggYDog7hqQGFHRcJCIlIHcIMLHAdJkESBwwHHATGUDbMiHb+kDbQ7emTYIkoDBlAFBBIORRQRUGe4o7cAQUpkSlFpUpAoNFc4NEZIo7lcI4cNHdgCOkI7/Hf4CVDjjveHfazPFxg7lgAABBAmQgMgBYQ7mAX4C/AX4C/AX4C/AX4C/AX4C/AX9JA="));
  },

  //tree_evergreen 10
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AVuAeTcAgEJDrcCLLYdeiQdbgizcDroC/AW7RdDvbvdDroCBgEADrMgDgI+aDrocBDryVagMAgIdahIdcLQIdbpEAhIdaSgIddpAdcoAdcAAId/DrYgXgEEwA+agMkDgYdXhMgDrcIDgkAiSVYgI+CDqx3BAYIdZAYVILLIDDLLeAoAdCd68AwBYCggdYyAdciAdCDSjvFeIQdcDSo7laLAdGiQd/DuUJkCVaGwLRbiVADrlIDrMBgECDokJDqskgRZDwAdVgEkaQodWABECDvT3BDqy2CgEEO7A2BDreSagIdYdoOQEQg7WAwJ3CSrBUCkAdXWAWQhIdCd6qwCyB6BO65WESrCwBDojvZawgdbhIdcDSQdjgiwWDohxVDo0SDTAC/AX4C/AX4CZogXVxIdKqIdOFR1IDrlQDrmQDqFIB5OUDqUEiQPH0gdRpMAiUJBgslkgdSkEQDo0pAYJGIHZMABhIdRkAdHHaEALIkBFQ53OKoMCBhGKDqQABBg9SAYOEDqMABgwDCDRYdHSouUAYMhDqjvDkoDCDqUIAQKzDDoVIEoYdPd4IdDBoVADqq2CWAQdBDRgdFoDUEBocSDqQACLIKwCDrWkBoWQDRrvKHYeEDqAA="));
  },

  //tree_evergreen 11
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AVdADv4CYpAd/AX4C/AX7v/AQ8AgAdbwECDreQiQdcLLmSDvbvdAX4CZoDv6HbjReDrEgiUAAAMBHDAcCAAId2wAddgQ/CSrA4BhIGBDq5XFHbTPCDrUAgmCWbcEWbOSoDRbDrx6DDv4CVOwQdYd4YdYWAYd3pAdcpIdfyCzciQhByDvYgECAYOADrMAhBZZkh2DDu+ADrVADYcCoAaTGQQdBiAdCpA4VHYpZVDIod5pAdbAwMgDrMEDrVJZgQdZZwUSoMgdoJ3YiUBDq+QVwkgiQJBd7UQhMEwAdaLgKzVKQJcFDq2ADwodWeQYdbHwodYTYgd3PQYdakECpAdakgddAX4C/AX4C/AReJDrVEyWRCiFSB5wNNsQdcsgddRRwdORRwdOB5wNMyYEBZIIdbpA7pgB3PHZVIgAdQpMUBg+QgIdPpgEBkRWIgEgDp1JAgRWIAAQdOmQEBxIJEoAdWYwmQDqhXDSQ4dShJyCAwWAoIdUOoa2CwEJDqmTLwsALKodEIAIbEDqOSsgECyJZBDq1MHYmQDoo="));
  },

  //tree_evergreen 12
  function() {
    return require("heatshrink").decompress(atob("0F4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/pMEIP4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX0EHf4C/AX4C/AX4C/AX4C/AX4C/AX4COgg7/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ASWiFlUliQOMomkGUQebxI7dlIebyI7dSzoccpQ7dogcbqQYVkAIGpA7bDC0ABA8SHbEligYVpEEBY8iHbIYWhEAN5FRHeILIyI7XlIDBoMkaSUAgGCHcADCoA7ToEgChI7WpQDCpDaJAStECytSAwY7fpAWU0QDCyEIgECHbtJLamkAwcAO79JkQ7Zgg7fkgTSkoyeARGJCaMpHc+RogTQHEoCDCCFKHdJ3QqQ7ppAQPHE4CDiQHGA="));
  },
];

// 13: grave_cross
exports.images[13] = [

  //grave_cross 0
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ATEggAdbgEAhId/DrEBDrkADrsAiQdcgQd/DuyVdaLkEDrgaXDokBDv4d2Srod/DrUAiQdcgQdcgEJDrjyCECodEAAhfTDsMEiA75DrOAK4OQDrI9CgUIDojRTAgdIeQodUgh8EDSRZFHYcSDqqSCDoQaUaI8JDq4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4ChA="));
  },

  //grave_cross 1
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AWkCDrVAgEADrQcBDr0JDrGQDoUBDrGADoUADrAcDDrAcEDq9IDv4d2SrrvfyAdcyQcCgIdZoAdBhId/Dv4d/ARmQd7mADoUADrAcDDq8JkAdXOIYAGDv4d/DqLxCgjOToAcDoMAgQKBd6jsDBQgdUKgQ4CwQdXyQ7DLK4CCDoSYCDq4bCaKoC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4COA="));
  },

  //grave_cross 2
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AU8ADrcAgESDrOQDrmADoMCDrIcBAAIddhIdXkAdDgAdWpAcEgEEDqtADoryWHYwd7O61JDgkBd7gdZwAdChIdYyAdCDSwCDDgMCDvRZboAd/DvMBWbkADrGQDocABAMEDqmADogAEDTQdRkAcMDpytCAA0IE4hWXpI7QKpodNzI6EgMkAYLKCK4NBkAOBBgIdKHoQNGhIFEgAGFDpC4GBAx8BDpPJAgNIBQlIDo2QgQdTawIdSLIVAR4gABiQdFAwodHyDKJEwQEBdhQC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CeA="));
  },

  //grave_cross 3
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AU0JDrUggEBDrUADrdIDoMADrNADoUEDrAcCAAIdXyAdEgAdWwAdFaiwcFDv4daSrkSd69Ad7eSpAcCggdYpIdCDS4CCkAd/Dv4d/d6cEDrFIDoUADrFADocSKaoAGgQdcAAYddgIdcTZ4dPLhodQgAdLkEAgkShDNDwBVCDgcEyVCHxSIFoINGawYdLwIHGHwQTGDpeQA40QBooFCpAdSgEJDqeSTo4ABTYYjCLJeSoCJCWATQJDpgC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CZ"));
  },

  //grave_cross 4
  function() {
    return require("heatshrink").decompress(atob("0F4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ASNAHfOAgEEHfEAHfMgHYMAHe46CgESHfUCHetIHYcAhI70oA7EgI70HQg7/Hf470hI70oA7EHGQCDHQcCHe0gHYUSHe0kHYQ41AQWQHf47/Hf47/Hf47/AUWAHYMCHfUAHesIkA6CHeg3DAA47upA5JggBBHdtAHREBgkQgA7tWJeAgESHdeQdxYABgQ7rNQIANHdUmpMggEJXAUEP4IFBoKyCBgQ7nmQHFpBwFggCBHeICJHf47rkDmBHfEAgQFByFAeQo7qkAECpA1BAAsBBYQ7qAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AVw"));
  },

  //grave_cross 5
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AXeCpMgDrMAAAYd6hAd3gIdcoAdBoAdYiVAkCVayEAkkAiQdaAAIaWAQWASwIaXSocCDTACCggaZAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ARw"));
  },

  //grave_cross 6
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CxwEAAAQd24Ad8gQdaxAbBhCVbiEJkDUZgGQHQIdZoB2CDrNJkEAggdakhaCDrWSpAdcAX4C/AX4C/AX4C/AX4C/AX4C/AX4Cu"));
  },

  //grave_cross 7
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AUtAgEAgIdZgH//0ADrUAuAd3yAdBAAMEDq+ADocADq4cE8ECDqsgDokcgAddTCocETC9ADY1/4AdTHI8BDrjUVDv4dZWY7RVpAcHhIaQAQgddwAdFDSYCCyAcEgQdWWwsSDq62EDSq2HDrFJDv4d/Dv4dViQdZgP4gECHbkADq9IDokADq1ADosEDqocFABQdLB4cHDquQOgl///gDqpWQDpUgBon/+AdVBw1//AbKGIIdOSoJ3HiAdTKJUAkj4INiNKDoLsIDhISHqVAgIdIaQoPJAQOKoEJDpQXJHY4NJDqGkyQdbymSgQ7ciQdZUoQNKyVEF4gFBpQGBB4QMBgmEDpdIAYMlA4NFkVSBoOJOgVJgEEDpZaPgAMLDp9IgId6hIdbgAPMDp8CDptIgEAJhWQiTANABQQCwDhQAX4C/AX4C/AX4CkA=="));
  },

  //grave_cross 8
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AWcAAAIdZkF/4EAiQdZuA7BDrsCDq9IOwQABDq9ADokJDq0HDokBDquQnAdEgAdVwLOBAAqYUwAcGTCkgDhAdTgfwDrhZcDrp2JDr0JHd7RJDSACDyAcGggdUyQdGDSYCCoAcEgIdWTAqwSTBQaVAQYcCgQd/Dv4d/DtcB/A7egAdYkAdcDgYdRyAFCpACCDokJDptACggAKiQdcHxgdKv////wAoMEAIOCDqdwAokEwD1KLJkfDII7CAAMBDpEQDhM/8AJHDpkgO4vAE5AdHpGQgAJECIMDKwQdPpOQgLhFEoIAKDpEghMiBIodUkkJii9KCowdJxI7GARYdKkmRDrQbBD4IdZyY7cyVkegIdapmCAgIGCBQL4BlJHEAoIdKpECTQeUBQMiqQXBGwYOBJJYdCLRwMLkAd6SYYdawIdcYwYdZfpdAgEADp9EAgQVBABJLPAX4C/AX4C/AX4CX"));
  },

  //grave_cross 9
  function() {
    return require("heatshrink").decompress(atob("0F4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AT8AgEBHfEf//4HfEcPAKz6gEEHe1AHYUAHew6DgESHemQHYkAHemAHYsJHfEgHesAgI4BgAFBAAI7xWIoABg/gHeFI/g8HHeXgHf47/HeQ6HAAI7wpI6Igg7xkA1BAQUEgEBHF4CDwB2FHemQHYsJHeeSHYo4yAQVIHQcCHetJHYcSHe0kHYQ41Hf47/Hf47/Hf47/Hc8/8ESHe8P4EAHfCzCgQ76gEJHGatBkA7DgMkwRxyABZ9qOIUBHZh9BHdAtDgkA/4AC/w8GHdFIHYbtEABEEHc9AGA0P/48JHc4uGgfwWwICBAAkQgESHcuQWAIvDg/8PQr4BAAISBgQ7l0gGEkP4OQsJCow7kkoGFkC5GHY+JHccpHauRHcYGGHYbkMHcVKDC9EHcNSB51IkAIHHcIPPpEABY8SHb+UCR9AgAzHkQ7f0gbaHb0ybBElAYMoAoIJByKKCKg0JHcICClMiUotKlIFBoqzBojJFHcrhHDho7sAR0hHf47/ASoccd7w77WZ4uMHcsAAAIIEyEBkALCHcwC/AX4C/AX4C/AX4C/AX4C/AX4C/pIA=="));
  },

  //grave_cross 10
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AQtEC6uJDpVRDpwqOpAdcqAdcyAdQpAPJygdSgkSB4+kDqNJgEShIMFkskDqMJkEQDo0pAYJGIDo9BgEABhIdQoEgDo47THQMQgIMHSqQCHxQdcqQDBwgdZAYQaLDpuUAYMhDrElAYQdcpEJDrD5DDrCwCDoIaMDpYDDiQdXWAQda0gDCyAaNHZ2EDqA="));
  },

  //grave_cross 11
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AS2JDrVEyWRCiFSB5wNNsQdcsgddRRwdORRwdOB5wNMyYEBZIIdbpA73O4Q7aDoVJigdZpgEBkQdZpIECDrUyAgOJBg2QDqgSHyEJggdPK4YdahIEBag8BDqJ1DWwsAgMADqGTLwxZCgAdWWwsALKOSsgECyLvWAQNMHZACCA"));
  },

  //grave_cross 12
  function() {
    return require("heatshrink").decompress(atob("0F4wZC/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4AgA"));
  },
];

