// Tile images, split from tileset.js so that each file uploads in one
// piece (see tileset.js)

exports.images = [];

// 18: locked_door
exports.images[18] = [

  //hay_pile 0
  function() {
    return require("heatshrink").decompress(atob("qF4wcCpMkyQC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CegAADiQdXDAdBgAdckkADrmQgAdcpECDrdJkEBWbAdDyEEDqRRDgIfBDoOSDqaVHSwIdahEAiQdaAoOADriVUDv4d/DqsCDrkAAAkQhIdVAYIVBoMgwEAkmADrOQH4Qd1gIdBoIdVSggdCgkQaLAfBDq0Sd4oddSqwdGAoLvUDrqzEAAgdUhJ3FoCVboFEDrjRbwAdYkESoKSBDqyuEkB3XAYIVBoIdgLKodHLwIdZwEBWwKVYAAIJBDqjvDHAOQpBZVDodBDoIcBSqgdGgKzVDo1BDv4dYoEAaLAdChEAiTRcyQdTgQdDDYNJkAdUDAIACHYIdByBZaDoMBDSAdJpBhDSrIaSDpB5BDrSyBDqyzEEQYC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C2"));
  },

  //hay_pile 1
  function() {
    return require("heatshrink").decompress(atob("qF4wcCpMkyQC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C2pEAAAYdXgUJAwUgDq0AyQdagADBDrNApAdawESDrUgkgdCyCzXkIdCgECgJ+DDqg0BLLMhkEAoB3agmSSrgd/Dv4d7gAdVoEggAAEDqcEyEAgkSHYOCBgIdTGgUkDvEChAdBgIdXkGCDoMQSrAdCHwLRYHYbvEkCVXDrMEyVIDvCuEWbMAwA7EoAdVwGILLQdBaLYdCTAIdbgEChMgiQdXO4MQWbIdCiRZBwQMBSq4dZKIIdbWAMAggdbpCTESqoVBpAGBgLvYDwIGBLIIdXwQddWYId/DqsEgAdakKzBoAdakjRbDoMSpEAgQdDgB3TDoUkyA/BAAQdSkmADoRZYAQNADrhwBDri1BDrmSWYgdYaYKzXAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ARo="));
  },

  //hay_pile 2
  function() {
    return require("heatshrink").decompress(atob("qF4wcCpMkyQC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CikEAAB0BDpgDDBIWAhIIBpASDgAdLkIdGyAMCDomAggdbwQddgAdoWaEChESHZ0CBgtIOQeAhANGDpAtGLIodQBgwdFoAd/Dq+AoI7cgJ3/DrB3RpEAiQdUkEAAB47NwQhBwAYGB4MJBwMADp4CBggXCiRZCDsDvNDraVEB4IdFBYg7NAYMAHZISBwAdPapDvESpodCiQMFHYmCd5od5OZAAJHZ6zCwGSgCzFd5gdHaQNEDrcADrkQDo53LkA7PwAdMUoodBwQdCBYhZNHAI7EgQ7EhJ3PDsjRFDoR3LDoOADohwBggdGoCVPABlBd58SBgrvFDrqVNDp6VNPZQ7VDpeADqDRCwDLBaIZZTDoTpCDvZ3BAoIdChAdKkADDwCVGkCVDDpivHAA8ChD9GLJAJCyAMCO4waHDuSaDDrGADpazECgbRBDosADRCzTgIdLAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AToA="));
  },

  //hay_pile 3
  function() {
    return require("heatshrink").decompress(atob("qF4wcCpMkyQC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CmwEAAB0EDpcAAYWQBIVACocSBYQdLkAMDDodIB4YdCyQdLkIdcgId5pFBWR6zLoCqEwAPGgA7OoFBLI7AEDp8JDpZ3PDvdChAdcd5B3/LKAdnkEAWaUAAB53LWYVBHYIYHHYIOBDqJWBAoWCDQIdOd4Yd5OAgdGSp9CBgg7IgTRNSoYdCZo7vPhI7FB4sgDv53LOI4AJd5yzEiESoDvELJodHwGSpAdbwEIDqLvGDoWCDqaEEHZeQLJinEDoWQO4SzToI7FSooOBDtCVDDorRGDpsJDo5wBDodILJsIRIgALDpY7CaIYPFkDvOSoYdZSoY7gOY4dPQggdXLI8gBIMEd4gdWeoIdwoIMDwBxBDqpuBAwUQSgwdDyAdKpFBVw4AIDpVJO4wnCB4ZZODr0hDrkgDrkkZYIdFXgizOdYizZAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ATQ"));
  },

  //hay_pile 4
  function() {
    return require("heatshrink").decompress(atob("0F4wcCpMkyQC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AStAgAAOgQ7qhIDBgIJCkESBgOABYVJHdVCAYVBHYYMCyASDHf47/Hf4CeoEAABw7rO4wCDyEJAoNIWeQ7Ed+w7/Hf47/Hf47/Hf47/HceAHd1AgAAOO9kAH5IPBiSztgg7BdIUgXISzCHf47/AUjrEHY4LDO9g/CO5ISBHd5vDAAY7zBgx30Hf47ydZAAHO+GQpEJkEBWe2QoAGBoI74oEEHfNBHfR3zoEAAAQ7CpDvDBYZ3sgh3FHYYPBiSztHf47BBQI75dAI7xGgQANO9g/CBgx3CAoI7/Hf47ndY47/WeGQpEAyVBd+2QpMgHf474eoQ7uoADDGoIAFBYVIHdY3HAA6zudIIJBWYIIBXILvxHf47/Hd9AhIDBgI7DiQMBwALCHdkAABw7qAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AVw="));
  },

  //hay_pile 5
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CIggdcwECDreSoEJDrdBgBcaDoMkwESDreSgAdYgQdCoAdYgEBDrZWBDrlAgESDrR3BgAdcWbQdhLLod/Dv4d/ARsAgIdcAAMCDrOQLIMQgAdbiQddLLgd5oC1CHbbvbgIdbyQ7cDvaxCWbUQHbgd/DrqVaoCzeiRZcDv4dZiCVaWIMCHbMCd4QdZyQd6yEBDrcAHbod/DrkADvMALLUAgB3bgKVbgSzcyQdgWbIdCwESDrUAggaWDodAhIaXAQWAgQaYAQRWaAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ARw"));
  },

  //hay_pile 6
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4ClpAdbyEEDrcJkhWagQdbgmSDrWBAgIdaxIdCgAdbgAdbyEBLLUggB3axEAWfLRhDv4d/Dv4dugEADrIbBDrWAkGShBZZwIdcxId/SrKxBHbYEBDrrvaDoUJHbgd4WYR3dhEgDv4dywIdcWYRZbkB3cDv6VZHbqzBgAdaAgMJgAdckgd5LAIdbhB3chA7dDu+BDvWIgB3dgDvdDrsJDwIdbWbgdayUEDrlIgQdbAQIddyEEDrZcBDrgC/AX4C/AX4C/AX4C/AX4C/AX4C/AVwA="));
  },

  //hay_pile 7
  function() {
    return require("heatshrink").decompress(atob("qF4wcCpMkyQC/AX4C/AX4C/AUgPOyIdc6QdV0gIF6dEDrlIDvVJiQdckQdZkwdBkgdSpodF2wdCxLvZyYdVO43StMkyKVbkmQDrmSggdcgAd6hESDrcJgQdcgAdbpMEhIdcwIdaoIdcpAdcLLVpAoUADrkEgIdcHa0mDq2mAodt2wdVpsk7YaBAQQ7WAQ2TDrEmAoXSpqACDpMAAAUIAYQdG6dJmg7MoIDBpACBoAdILJodugUJDrcAoAdbiEJgAdZ0kQoMAgIdPk3btu2zYCB6dpDqgPHHYhZTAQZ3DDvdAO5KMCAQg7Ld5QGFHwQdHiVJDrlIDq82Dq0mQAodVARUAAAKzIBYQAEHZIbBHZMf//AgEId5EmDoUMaJXt234SQYdGWYYdLJgPfQwIdMggdKtkA7YdasEAjYdPoCzJsEQDqFBgA7bDpR3OAQOkDpmADosm7a9BzYCB6dpDqgMCkxZE0jvBDrizLO5IdFkkApDvJsgdQBwIdJHaIdLUwPZDrQECDp9ADpMAAAIdN2kQgIdJ7ZaBAQhpIWYIdKAww+BEwvTtIdBoIdRKwYCBDocQDqQPFkwdcSoIdEgIdOAQ4dDgMAaJcAhADCDpUJd5gdPpIdJwBjCOgVADpMCDpWSoIdNAQMSDrgFBgkJDrUJgDEIDqZ5BDrUIPIIdagAaGDssAAAIdKggdJDAQAEDpOQDQ47DBJACE6VpkmRDrOTAQOJDqNN0gIE2xZCDqVJDosmDoRMLDpqVCkQdciQdbpCmMDttEDqgCG6QNMDp+RDpoC/AX4C/AX4C/AU4A=="));
  },

  //hay_pile 8
  function() {
    return require("heatshrink").decompress(atob("qF4wcCpMkyQC/AX4C/AX4C/AWWkB5wNMksmDrcp0wJFyYdUpId5pQdcqQdcAYOm6QdYygdC7YdFtIdU0jvZDQNNkx3ZAYSVZkIdcgId5pFBDrdCDrkCDreQwQGDDq+EDr0JDreALPUCAwVNDq+AHYYdYLIgdf6Qdc7dtBgfTDrG2AQWStIdU0gMFARAdLydpkwJCPQodRzVJWYYdCyEAAANAAYUALJgdIhICBBwQFBDs9BgAdawEIDrcCoEgDrOAgUIkGTDrtN03btu0AQO26BZRHYYMGO6QdBO4odxwEAHbmCDpWSTAKbCAQQdJpI7KCo4dIwAdi7QdcNwvQDp6zBgIdCBgwCISpMAgA7JBYMAoADCgDRKjAdC6TvKwf//AdOWYwdEju274dKhAdNkHtMgIdatuAjazJDqFsgEDHZECDqMCDrg7NyYMHO6AdEpum7dt2gCB23QDouQDpcYHYJZD6Q7IDpKzCDrWEwFIgCVFDpCVBDpQOBDp6VKDqQ7clu27YdJhIdPCwQdIwUAkGbDpsAAAIdKWYNtBgwIBKgICEDpMIDoNN0wUFHAIVGDpR3BDoQME6AdWOgQMCHaGADooMFLKMCDpQCILJNAHZTMCoACBU4IdJpAdcpLRDDo0JPQcAAoIdKHYNJDpmSDpOQDoIGCDq+SgVBDrdCDrlIDrlJgId6kIdckgdKgAAGDpWkyVNkwMIAQoKKygDBEAIdb03bBImTtIdRyQdC6QdFHaWSqSVHDqlKDrlJDvcpDrklkzvZAQWkDrgC/AX4C/AX4C/ATI"));
  },

  //hay_pile 9
  function() {
    return require("heatshrink").decompress(atob("0F4wcCpMkyQC/AX4C/AX4C/AX4C/AX4C/AX4C/ATdSDzciHf47/Hf47/Hbc0HffSHeVpB4u07QOMHb9N23btoCBtIFEtu0Aom27QFEAQOiWdYCOWc2kCpeaWcw7/Hf47/Hf47/Hf47/Hf47/Hb20CpfaHf471kw7syY7Oto7/Hc3bHfFN2w7BAQIICtoFBAQg7BJQo7eqYvFHYQ4HAQXSBA2iWcYCWWcOTpoGBtIVNBwIUDHc8AABcSHdsEBgMgAQ8kHf47/Hf47/Hf4CSqdt23bpoCBtOEHZcaCgtt0R3gBIh3NCgyzhAwazNjSzBHdazNHf47p23btoCJ7Q7t0gVLzQ7ryY7/HZS2BHcdTcYo7QfAmid8gCVO82AgEAkACBAAYJCjR3qkw7BwgFBkGSoP//g4BCoQ7BO8izGHYsO7dvxIFBHYVpHeGQuymB+I73m3AhuxHfEAgI75gI76O49tHddJgjvLiQUGHb1Ttu27VN23bO43IHYp3BCIIUCtuiO8GbpqzCO4o7GiTvByYUCWcQmDHf47CgA76oB3/HesW7dtyI73iQMBHd2bHZEAAAMBHdoJEmyuB2wCI6QUGHb1TF4tJ0gVLzREG0R3iOgNpHaKznyY7PWcg7/Hf+AgEAkACBgAGCAQUatI7qyQ78wgFBkGSoEAAoYOBHeYCGHf47/Hf47/Hf47/HcMAAAI7uwAyCABA7uCpo7sASo7fpu27dtAQNpAolt2gFE23aAogCB0Szr2naWfM06SzsHZrvtDzY7/Hf47/Hf4C/AX4C/AX4C/AX4C/AX4C/AX4C/AR4A=="));
  },

  //hay_pile 10
  function() {
    return require("heatshrink").decompress(atob("qF4wcCyVtkmSpICCkwFCxIKFARQdLyIdZ6QFCDrEkDruaAoVEDrGTAoVIDrGStIFCiQdYpoFCkQdYpOkDrk0AoQdZAQeJDrSYById/DqwLBDrbyBDrbyBO92kDvHaHdLRRpu2DrdJm3aDrck7ZuBDrWTPRAdRgIDBPRCzRhEEPRIdRhMgiR6IDqeAPQYdYPQiYESqIdCpB6D6QdXpJ6EDrEkgB6FDq0SPQodXPQgdYPQnaDrB6DHYOkDq56E2gdYPQVpmwdYpIdCknRDrcmHbgd/DuuTDvXbtumO7dJk3RSrckWbgdQpO2NwO2HbIGDEAQCCDq4CGDv4d3todbzdt0jvQB5gdPgAAIgjyBHaAVBwAbEiVJgmTSqUgAwMH/4hBDoSzTDoNIndtCoIdYoJwB2QdZh4degIdah3YgEyDvMgDomTto7cpMm6IdZXQOmHaazGydpkwdaSoId/Dv6zxDoMk6IdS7AdHmw7TDo2Spu0LLMk7dt0g7XgVJm2TtskDqkNDoJWB0iVCLKltDoIaCDq9syEk7QMBDqsP7MkhM2BgQ7WpECOgIdYgUEC4QdDAQIdSgJ0DDq8SdIIMFDqbpDBghfBDqZ0FyVADqp0FyEADqh0GgEJDqYJGgECO6x0EgC5BDrB0CDodtDquAgMkDrMggAJBDrFISQQdEfAIdSgCSCDoNIDoWkDqOADotAkmTpo7ROgMBDoiYByR3ROgKSEkkQDoR3RKwoCBgCACDqYGCDoYMCDqUgDorUCBAWJSqAdFAQM0BAQaLDpQFC0gCBkQdWgmSdgIdYpCSDBAJhCDqdBkmTBgVIDRgdJdgOaBgVEDqsQAQPSBgQaNDpDsBkwdZkCNBkwMCyIdVgACBDoeJDqAA=="));
  },

  //hay_pile 11
  function() {
    return require("heatshrink").decompress(atob("qF4wcCpMkyQCNygDC6QMFtskDqGkDrclAYUmDroMGDqMpAYU0DrADDPQYdUpQDCpoMHDqFSAYVpDreTBhAdQAYWaDrGUFRgdPVoKSIDv4dQCIIdbdhAdTdhKV9yYd8mzRaHaQdK7bdBDrM27QFBDrFN2wFCDq50BBYIdRWY50CyUBDq50DwFBDqx0DkESDq50CpEEDqSVEyZ0EDq0mOgYCBDqx0EDq50DgAMCDqh0EkAdXOggdXmx0EDquTO4R0DDqubOgwdV7VNOgodU02SDoOCDrGk6Qd/Dv4dW0gd46dt2wdZ03SAYI7aySVcDs3bQAPbB4IdRC4YCBB4Y7TB5Id/DtdtDreTtu0HbYPNHaG2wEAAA8BSqOkwVJkAbEggdTkgdDgP/8QMBiTRTDoWSgXbvgdZyEW7dvxIdc+Ida4AdcgENDuVtd4YdBgIdT03SAYI7a6dt2wda6VNLIvAtodVaIwd/Dv6zp02SDo0AHanaDrmbtJ3bydt2wGBHbGStpcBpMADrB3ByZcBLK4dCAQQdB7YdYpM2yECrYdZknaoEJl4dZPQMAggdUpIdDEYWAiIdZPQOSgIdaPQNJkAdUwQJEeoWSDqeAhIMETwQdUgAMFPQJZUoEAPQx3VgECB44dTkEAPQo7RtodDPQwdWyUAggdbpEAiQdUcwIdDTAMADqeTDoOADoaYBgI7TtOkyEJDoh6CO6QGBgIdDgQeBiR3SAwMADoaYCPQQdSoEADoZ6EDqQ1BDokkDqGUAwgdGiAdPyQDCzRWEBASVQyVSAYOTC4QdZeQMkwQdWpQDCTAOQDq1JAYa5BhIdWlIDCmmSoIdWkoDCkzyBDrfSeQYdTkh0BAYIdBkDUBDqmUDokkgQdE"));
  },

  //hay_pile 12
  function() {
    return require("heatshrink").decompress(atob("0F4wZC/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4AgA"));
  },
];

// 19: death_speaker
exports.images[19] = [

  //death_speaker 0
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AQuQgAdagEN00EDrPggEGDrUcgO0DrXwgB3b/+AhIdcgIda/kADrbuBO7ech6Vc//gDrf+HbfgO7gcBgEEDv4d/Dv4driAeCHbgd7WfYaXDv6V9Dv4d/Dv4dRgAd/Dv4d/Dv4driQIChIdYAAsCDq8QDrcEDrhZeDreQDrIfCgUIDojRTAgdIDYUBd6gBBgheEDSRZFHYcSDqqSCDoQaUaI8JDq4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4Ch"));
  },

  //death_speaker 1
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX9IDreCoAdbsAd6xkADreRDrmSDrrRcHbwd3yEBAoNEDrGP/AFBo4dYn3/ghZamPYDreB4Ydbw0ADreQg4dBoDsZgcAAAI7Z4EAgP/DrI5BDrWSn/gLLWSng9CDrUQDrcAkAdbjEkHbgdcn8EDrc4LPQ7BwAd4DQI75jAdcoAdcpAdcAQId7gAd/Dv4d/AR8gDrEJDrGQCoIADgIdcAAYd/DuckwEAgjOToAcDoMAgQKBd6jLCgAKEDqhUCHAWCDq+SHYZZXAQQdCTAQdXDYTRVAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ARwA=="));
  },

  //death_speaker 2
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ASVAgAaYpEAgE2zESDq2CoEDwEAjAdXsFAjlwg3QDrOT4BbBO6+MgH//0AWDGRgHzDoMEWbEAz/wDrVIgTuBd7MAgVwngdagf//+AO7X//A7VyEBAoNEHIJ3Wx/4AoNHDYIABiQdTn3/ZYIcDDqsx7AdbwPDDreGgAdbyEHDoNADrGSgY5EHa/AgEB/4dZC4IdCLYUCLKk/8BZFDqs8HoQdaiCVadgMgDrcYkgdFDSQ7DDrk/ggdbnA7GSqwdcHYOADvBZBHfMYDrlADrlIDrgCBDosCDugcEDv4d/Dv4CLkAdKggdXAA4d1hAdSoA1IhAnEDpmAKZNJHaBzNDpuZHQkBeIbQBK4NBkAOBBgIdKHoQNGhIFEgAGFDpC4GBAx8BDpPJAgNIBQlIDo2QMAIdSawIdSLIVAghWCSoUSDooGFDo+QZRImCAgLsKAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ATw"));
  },

  //death_speaker 3
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AStIgESDrEAgEG6cCDq2QHANwgEDDq+MhEDx0A7QdZiV4LYJ3XyOAj//4EEWDEgj1/4EADrFAif+LILvZgC1Bd7NAgFOg+ADrV///wDrMT///LK0AAQNIz/wO62R/7pBpHgDgMAgQdTw/f8B3CDq+GnbpBDrOQnFgDrfAHbazBO4NIDrNAsAbDDq8YDAM/aLBZBDocIAoQdUo/8LIodWHoYdZwSVboEEDrdDgmADokSHawdbo/gDrg7GSq4dbHYOQDvBZBHfNDDrlIDrlJDrskDosADumADv4d/Dv4COpEkDgodQCwwAGhIdyhAdGgIdTgQdHAAIdToBcJO7QADDpcggEEiRXBiTxIBwOSoQ+KRAtBBo0CAoQdLwIHGHwQTGDpeQA40QBooFCpAdSgEJDqeSTo4ABTYYjCLJeSoCJCWA7QEDpgC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CZA="));
  },

  //death_speaker 4
  function() {
    return require("heatshrink").decompress(atob("0F4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CrwEBHG2QgEAtswHesEwEHHgI71pHAwE48EN0A72wMnwEAd+0YgP//kAHGYCCkUB847BhI71kkBn/gHfGQgjv4kkAgngvA74g///473d4P/+A7zkECAoOJ/8Ad+kf+AFBxw6BAAI7xpF9/0Jd4I72sewHfFJgeGHfMMgA75kEOHYOAHe0kgx1EHekhOgMD/yz3GoI7CWoUEWeV/4CzFHed5PIQ73vA7Gd+UkgFAHfMwpA6EgJ30HfV+hA75uB3Fd+izGHelwpI7/Wex3/He0wHfWAHfWQHfQCBHYsEHf4CvpA7/Hf47/Hf47/Hf4CiHQo7zHIwAEWGp4EPV9AHREBgkQgDs0WImAgESHdeQdxYABgQ7rNQIANHdUmpMggEJXAsEyVBWQQMCHc8yA4tIOAo+BHeQCJHf47rkDmBHfEAgQFByFAeQo7qkAECpA1BAAsBBYQ7qAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AVw"));
  },

  //death_speaker 5
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AXeCpMgDrMAAAYd6hAd3gIdcoAdBoAdYiVAkCVayEAkkAiQdaAAIaWAQWASwIaXSocCDTACCggaZAX4C/AX4C/AX4C/AX4C/AX4C/AX4C/ARw"));
  },

  //death_speaker 6
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4CxwEAAAQd24Ad8gQdaxAbBhCVbiEJkDUZgGQHQIdZoB2CDrNJkEAggdakhaCDrWSpAdcAX4C/AX4C/AX4C/AX4C/AX4C/AX4Cu"));
  },

  //death_speaker 7
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4CogEEDS0giVIgGR23ADq0bgAABgMAzESDqsYDoQeBjAdUyBZBgP/DwXQDqmMhMgh/AwEAkmAO6mNwMghM/yA7BWauRG4MJ//8DoLpVyE24EPDoUBDquSgmAhMnHbGSoEAHYYdXaIMP/iVYDoQ3BzjwCDrEEDrNIDAMH/+P8g7XDoMn/6XCWa8Jn4dB/5ZYp7RDLK8Cv/4DgQdXiV/4AdDiSzXAAgd7gQdypId4ggCBkAdcHbTIBDgzRU/kQgH8DrMAwEH//8mgdXSQIdDwB3XDocnDocADqQXDhDTFDqzRZjAdcaAIdbOQodXkgdId6Yd/DvGADv4d/Dv4CQyAdcyQd/DuyVIgQd/DtuADv4d/gAd/Dv4dVABQd/AQgcTDpEgDrgbTGIIdYiAdZCQskggdSiQSFpQdBWAwdTqVAgIdIDxQdGxVAhIdaHYIaGDoYDBpAcFCQ2kyQdNpLBBAARsHymSgQdNkmAZYw7FMIwdIARQDByANKyVEF4gFBpQGBB4QMBgmEDpdIAYMlA4NFkVSBoOJOgTDBggdLLR67HDqlIXY4dzhIdbgAPMDp8CDptIgEAJhWQiTANABQQCwDhQAX4C/AX4C/AX4CkA="));
  },

  //death_speaker 8
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C6gEEDS0giVIgGR23ADq0bgAABgMAzESDqsYDoQeBjAdUyBZBgP/DwXQDqmMhMgh/AwEAkmAO6mNwMghM/yA7BWauRG4MJ//8DoLpVyE24EPDoUBDquSgmAhMnHbGSoEAHYYdXaIMP/iVYDoQ3BzjwCDrEEDrNIDAMH/+P8g7XDoMn/6XCWa8Jn4dB/5ZYp7RDDqUAAocCv/4DgQdRgf+gIFCiV/4AdDiRTPv/3/CzEAAgdR24dogTpQv0ADrUP/3YEYYdX+BZCDrEj2HbggFBkAdWkkCnYdCHa8kwDICDgzRQAQM2/f8iEA/gdXmAUBwEH//8mgdVwE4SQIdDMIR3Sx/ACoIdCk4dDgAdRn4XDhDTFDqP/GojRWx/8jAdayPkaAIdZyEAOQodWgMkDpDvRyHBDrkADreHHbmH/AdbwCVBwA7cDrTRCDrWOhIdbwAdcwwdcx7vBHbuQDrmSaLQdcyJ3BDrWSLLo7BSpECHaYdbHwQd6wAd/Dv8ADv4dkyAFCpAdWoASIABQd/DrMJDrkBDpEQDyYdMkAdXpGQgAJEDqtJyEBiQnGDqcghMiBIwdTkkJigdQiQdJxI7RDpckyKiIK44dJDYIfBQhAcDgIdLyY7JAQOADgIIDCBOSshRBBhICFBRVMwQEBAwQKBfAMpI4gFBDpVIgSaDygKBkVSC4I2DBwJJLDoRaOBhcgDvSTDDrWBDrjGDDrL9LoEAgAdPogECCoIAJJZ4C/AX4C/AX4C/AS4="));
  },

  //death_speaker 9
  function() {
    return require("heatshrink").decompress(atob("0F4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AUlAgA41gVJgESm3YiQ7zkdggAABkETIII7zHQQABkY7zhMkgE/8A7BjQ7yyOBkkB/EQgEEyDvyyOwHYMn+S0CdmICBmEAgM//+APAI7zg3YgP/HYQ4xAQVAyEBkh33pCzBO4Y70AQI7ByUAAAI71OYOTO4MAiQ71gA74V4X/+P8wA70kCzB/4ABHelIgEBk47C8Cz1hJ1Cd+OAhKzDp//eQQ7vkF/4AFCkVP/A7DgQ7th/+/8EWYQAFHd/2Hf47GgDvuh/AHfEh//bHYUgHev+j474kl2jdgAoQ71wFHHYR32yAxBgVAHQ0CHd2G79/wUAj+AHeoyBiEA///ww9DHd+Qg8EGgI7CXYTvwyP4GYQ7BwnwHYcJHd3nGocBPgQ7y/5xEAAqzv/+DHfGSnmCHfMAdQo71kmAHQ8CHd8YHfSzBHfGQ/B35yH/O/UAAQR35HfGSO/WR4Kz6gI76O/WR/B38yQ77oA72yUBHfU4HfVBHfUYAQI6GAAJ3yHfACCHf472yA7/Hf47/HfEJHf47/Hf4CkiA73G5A+xkAtBgI7MgI7pFoZ4NHdFIHaMEHc9Adx4ACHc45RiEAiQ7lyCwPAAISBgQ7l0jzHAAw2FHcklAwo7PxI7jlIGFkA7OyI7jAww7PyQ7ipQ7Xog7hqQMJHYwOGpA7hBhY7MpMSHb+UBheQHAMSoACBBw0iHb+kDbQ7emTYIkoDBlAFBBIORRQRUGhI7hAQUpkSlFpUpAoNFWYNEZIo7lcI4cNHdgCOkI7/Hf4CVDjjveHfazPFxg7lgAABBAmQgMgBYQ7mAX4C/AX4C/AX4C/AX4C/AX4C/AX9J"));
  },

  //death_speaker 10
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AQtEC6uJDpVRDpwqOpAdcqAdcyAdQpAPJygdSgkSB4+kDqNJgEShIMFkskDqMJkEQDo0pAYJGIDo9BgEABhIdQoEgDo47THQMQgIMHSqQCHxQdcqQDBwgdZAYQaLDpuUAYMhDrElAYQdcpEJDrD5DDrCwCDoIaMDpYDDiQdXWAQda0gDCyAaNHZ2EDqA="));
  },

  //death_speaker 11
  function() {
    return require("heatshrink").decompress(atob("qF4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AS2JDrVEyWRCiFSB5wNNsQdcsgddRRwdORRwdOB5wNMyYEBZIIdbpA73O4Q7aDoVJigdZpgEBkQdZpIECDrUyAgOJBg2QDqgSHyEJggdPK4YdahIEBag8BDqJ1DWwsAgMADqGTLwxZCgAdWWwsALKOSsgECyLvWAQNMHZACCA"));
  },

  //death_speaker 12
  function() {
    return require("heatshrink").decompress(atob("0F4wcBkmSpIC/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4C/AX4Ck0QsqksSBxlE0gyiDzeJHbspDzeRHbqWdDjlKHbtEDjdSDCsgBA1IHbYYWgAIHiQ7YksUDCtIggLHkQ7ZDC0IgBvIqI7xBZGRHa8pAYNBkjSSgEAwQ7gAYVAHadAkAUJHa1KAYVIbRICVogWVqQGDHb9ICymiAYWQhEAgQ7dpJbU0gGDgB3fpMiHbMEHb8kCaUlGTwCIxITRlI7nyNECaA4lAQYQQpQ7pO6FSHdNICB44nAQcSA4wA="));
  },
];

