// autogenerated with scripts/generate_images.py at 2026-09-28 16:05, do not edit
// Treasure icons, 32x32, see treasure.js
// Art by Clint Bellanger, CC-BY-SA 3.0

exports.images = [
  // 0: gold 1
  function() { return require("heatshrink").decompress(atob("kEgwcBkmSpIC/AX4CdgEEBZGR//ABZGP23YiQLHxoLKyO2EZI7LAX4C/AS4=")); },
  // 1: gold 2
  function() { return require("heatshrink").decompress(atob("kEgwcBkmSpIC/AX4CFoEABZM/7ESBY+R+3bgQLI2wLKm3aBZOkyYLIyU2HZJTMAX4C/ASwA=")); },
  // 2: gold 4
  function() { return require("heatshrink").decompress(atob("kEgwcBkmSpIC/AXNAgALJn3YiQLHyP27cCBZG2BZU27QLIx+kyYLIv+mC5N9C5V90xTJtuANZNtepWAhLF/AXoA=")); },
  // 3: gold 8
  function() { return require("heatshrink").decompress(atob("kEgwcBkmSpIC/ASmQgALJx/2ggLIvu24ALItoLKpu2wEAhILGtMk4dtwIXIjdt2AXIBZIXBidt0AXIjVJmALGxoXKKIIXJHAMjKY8j9u2ghrHCgILBR5JcHHYcBf3gCo")); },
  // 4: gold 16
  function() { return require("heatshrink").decompress(atob("kEgwcBkmSpICxgEEBZGR+3ABZGP23YiQLHxoLKxO26AXJkmYC5cAC5VshIXJtuBBYsgUAOYBY8btk26AjGpHbtuEzA7GBYWGL48AzdtgmAC40w6VJwwyBF4swC4MAEwJHFmGQfIILI4f9wAaBMYILEj/t2AyBC4sAj9t2A7BhEAKwkbBYIxBo3bgQLGd4M27dgBYcjO4ILIkkAm0EyQjGkhgBSoQ7FAUAA==")); },
  // 5: gold 32 (chalice)
  function() { return require("heatshrink").decompress(atob("kEgwcBkmSpICwyA6BgQLHhu27dghILFkdpAgNNwILFjdJk3apuwBYsepIjBBZdJBY0b/IvC0ALFidv//7tMgBYsStojBtMwKY1N2gEBKY0jC4QLHkgLB6VMO40kxu2yVgTZABBTZGSomAWxNGBZfABZMG4ESBY+Bm3TgALHL4PathfHt4LBpALHwILBEZGSgEAHZAC3A")); },
  // 6: gold 64 (bars)
  function() { return require("heatshrink").decompress(atob("kEgwcBkmSpICzgALJkdsIhMbtuwggLGgHbtu24ALFyOmBZONmwLJtO2BZEjpoLDHYsaBAILB2nAiQLCpHTBYPfto+BNwdG6d/237to+BtkJBYM2zdv//bHwQLCyO2zdt3/bHwQLD34LB23aHwQLCxu3+QIBHwXbsB0CIgPJEwQLBgQLD7dhkhfB+3YL4WQJoNhm/7t6DFoHbhO2//9QY0AiImB/uwa4xiBF4OBcY8GQAgLFpEbLgT7HkBcCBY4Cp")); },
  // 7: gold 128 (chest)
  function() { return require("heatshrink").decompress(atob("kEgwcBkmSpICkwApJkF90EEBY8Cvu2wESBY0jgO2/UABY9Ig3btAyHtMgjdtGQ9pJINt2/ABYuNknSgO0yA+Fxsm6VIAQMCBYmRm3apOmBY0NwHbtM0BYsDtM2gdt2gLEoAgBk3Yhu2zYLCyE/yVP+mSsE2zBHCyP2FgX7pOAwBED2wLBAQNJ20ABYtN0mSAQJ3DC4c2yYCBBY1t0n+pu2BYm3/VtBwQLEyCABBYanFoAUCC4yDCBYhTDTYYLCwDjGGQPbsEJBYwyB7C8FAQgsGASwA=")); },
  // 8: gold 256 (crown)
  function() { return require("heatshrink").decompress(atob("kEgwcBkmSpIC/ASsJBZOR4MkiQLHx+wkcCBYtAkmBwALCggLDo0EC4MDSAPABYdHggXBjVB4GAC4kAsOG6VhwEABYkahuEyVBwgjEC4Nt2GShoXG4dtn8Shu0C4vbtOm4FtBZG27YLItumAQQLF/dvmwLI7d/EYU2BYlIjftBYWwR4lJkF/+3btkBWYxnBAAL+vAU4A=")); },
  // 9: gold 512 (sword)
  function() { return require("heatshrink").decompress(atob("kEgwcBkmSpICIkECBZMj8ALKtEJExNtGRWN0ALJyO0gmSgAOHm2AyOwBY9G6ENBYOQDQtI7UMHwOP/wpBDQcbKwV923AC4kb5OAgENBYtH7VN2H/9O2gALDn0Ct+2jdtkgXEm0Etv24dtmwXEJoMN33YsDBBiRiEsO34EP4//XgdIgVMm0T9k+7dgUgVH/9AgHTtk27dhwJHC7cP/0Stkm7dBBYRBBNAPDpE0yQXDoH7sILBC41H7YsBwdsC4tGBYJ0BgAXBoBHCn2btB6ByQXBsDjC/2SpkAkEADoJrCyP2C4MJj/8hCDDBYIXBhH7to4CBYSwBsFI7YLG2kAFIMbtjmBWYoFBHYKwEARQ=")); },
  // 10: Wood Stick
  function() { return require("heatshrink").decompress(atob("kEgwcBkmSpIC/AQWQhILJxJTKpMgBZEitILIpETC5NEAgIvHyEmDIJHHhM2yUAHA9N2mQgQ4HtskwESBYsEzZEBgAsFwMk7VJgBxH22SoBQGgVN0mQIg1Iydt0mAIg1E7dpkkAIg0kBYMgghEGkxEL7REHPoSJBSox9B2xQHBZkStu0Lg4LCLhA7CUI4CBkEJgALIEIMAOgwCBA=")); },
  // 11: Spellbook
  function() { return require("heatshrink").decompress(atob("kEgwcBkmSpICXkAiCiQLFpAHDBwUCAwUEydt23bA4QLDkmbBYQCB6QLEFAM2BY826QECC44jBDQUmEY+27QLFyO2CgRKBBYwUCyVNBYumLgXSBYuQm2bAgOaBYp+BC4QvGI4IEDC4ygEHYxTCBZJTBBZBTDBYxTEBY5TPNY82I4SDGC4PbtKbD4CDEBAJiBBYRmDpEAWYPbBYISBBYQCBgDvCk0EBYomBiVJkALHpMAhMgBAoCDwAnCBY4CE")); },
  // 12: Magic Sapphire
  function() { return require("heatshrink").decompress(atob("kEgwcCpMkyQC8kBGBBY9Ig1JluABY1Dy1JkuyiQLFj4EBkuSoQLEyH/+XJnooBBYmH//+7d8A4MJBYwjCBYsLs/yAgOypNhBYcJkuT7Mk2wLHyXJC5IECBaZcBpMnBY9kAgIOCBYmBAgPbBwNLL4gLCI4ILGyCgErCnFgizBAgPCBYtAAgWWX41IgSbBa47vLAX4CEA=")); },
  // 13: Magic Emerald
  function() { return require("heatshrink").decompress(atob("kEgwcBkmSpICmkECBZMcgALIpH9kEJBY9H/skKBE//kkwALGyH/tN0yEEBYuG/cJh2SgALFu/YKgI/BiQLDkf24QGBMAJiEj+2iRRBwFIMQdI/+wyALByFABYZcBwmAAwVAkBcD9kkCQWagIvCyAsBkALC6EII4QLCgASBk2AoBfDgAXBBYM0gB3EgEBkwLB0EAR4hMBkvCpoQBXgoeB3/oFAKnFgEAyACBdg8AiVAd5CuBUgoCDwi8Ha4eSagxiEBA4CtA=")); },
  // 14: Magic Ruby
  function() { return require("heatshrink").decompress(atob("kEgwcBkmSpIC/AS5gBggLGoECpM/BY2QAgNP/gLGhM/+VIkgLFgf4EoUEBYlI//xBYQXFo///ILK5IEBuMgKAkk//IAgMJBYsAzwgByeJBYsgj0AkmcpLUFkkeoMk/gLHHYMn8VIhILGAAMSBY1E/1Jk5fBUgtI+QECVAK8FiV5k+QiQLGkF5n8AahGAMAL+mAUo")); },
  // 15: Magic Diamond
  function() { return require("heatshrink").decompress(atob("kEgwcBkmSpIC/ARGAKYQLGkF/////xcGj4KB9///ALEpAWB/YCCggLDod//3fDIP/sALDn9vBIX/7f8iQLByP/9u/HYQaBwQLBx//v+27dt237//wBYQ4BC4W3CIOwBYOQ7f/+///oLBtojCyUb/++GQP2/47DKYP9EQNvHYJTEpFtBYJiBNYtJh5eC+6DFpMjBYfBWYynC30JBYxuB/5cCBYqGB/pcDAQs/LggCFo/geRNILgoC7A==")); },
];
